// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hmac_verify_preProcessingOneTripForHMAC23 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        opad_buffer_0,
        opad_buffer_1,
        opad_buffer_2,
        opad_buffer_3,
        opad_buffer_4,
        opad_buffer_5,
        opad_buffer_6,
        opad_buffer_7,
        opad_buffer_8,
        opad_buffer_9,
        opad_buffer_10,
        opad_buffer_11,
        opad_buffer_12,
        opad_buffer_13,
        opad_buffer_14,
        opad_buffer_15,
        msg_key_strm1_dout,
        msg_key_strm1_num_data_valid,
        msg_key_strm1_fifo_cap,
        msg_key_strm1_empty_n,
        msg_key_strm1_read,
        len_strm2_dout,
        len_strm2_num_data_valid,
        len_strm2_fifo_cap,
        len_strm2_empty_n,
        len_strm2_read,
        blk_strm1_din,
        blk_strm1_num_data_valid,
        blk_strm1_fifo_cap,
        blk_strm1_full_n,
        blk_strm1_write
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [63:0] opad_buffer_0;
output  [63:0] opad_buffer_1;
output  [63:0] opad_buffer_2;
output  [63:0] opad_buffer_3;
output  [63:0] opad_buffer_4;
output  [63:0] opad_buffer_5;
output  [62:0] opad_buffer_6;
output  [62:0] opad_buffer_7;
output  [62:0] opad_buffer_8;
output  [62:0] opad_buffer_9;
output  [62:0] opad_buffer_10;
output  [62:0] opad_buffer_11;
output  [62:0] opad_buffer_12;
output  [62:0] opad_buffer_13;
output  [62:0] opad_buffer_14;
output  [62:0] opad_buffer_15;
input  [511:0] msg_key_strm1_dout;
input  [5:0] msg_key_strm1_num_data_valid;
input  [5:0] msg_key_strm1_fifo_cap;
input   msg_key_strm1_empty_n;
output   msg_key_strm1_read;
input  [39:0] len_strm2_dout;
input  [5:0] len_strm2_num_data_valid;
input  [5:0] len_strm2_fifo_cap;
input   len_strm2_empty_n;
output   len_strm2_read;
output  [519:0] blk_strm1_din;
input  [5:0] blk_strm1_num_data_valid;
input  [5:0] blk_strm1_fifo_cap;
input   blk_strm1_full_n;
output   blk_strm1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg[63:0] opad_buffer_0;
reg[63:0] opad_buffer_1;
reg[63:0] opad_buffer_2;
reg[63:0] opad_buffer_3;
reg[63:0] opad_buffer_4;
reg[63:0] opad_buffer_5;
reg[62:0] opad_buffer_6;
reg[62:0] opad_buffer_7;
reg[62:0] opad_buffer_8;
reg[62:0] opad_buffer_9;
reg[62:0] opad_buffer_10;
reg[62:0] opad_buffer_11;
reg[62:0] opad_buffer_12;
reg[62:0] opad_buffer_13;
reg[62:0] opad_buffer_14;
reg[62:0] opad_buffer_15;
reg msg_key_strm1_read;
reg len_strm2_read;
reg[519:0] blk_strm1_din;
reg blk_strm1_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    msg_key_strm1_blk_n;
wire    ap_CS_fsm_state3;
reg    len_strm2_blk_n;
reg    blk_strm1_blk_n;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg   [0:0] icmp_ln1065_reg_1249;
reg   [0:0] icmp_ln1065_1_reg_1253;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln1065_2_fu_1006_p2;
wire    ap_CS_fsm_state8;
reg   [511:0] reg_523;
reg    ap_block_state1;
reg    ap_block_state3;
wire   [4:0] tmp_len_V_fu_533_p4;
reg   [4:0] tmp_len_V_reg_1244;
wire   [0:0] icmp_ln1065_fu_543_p2;
wire   [0:0] icmp_ln1065_1_fu_549_p2;
wire   [63:0] grp_my_switchEndian_fu_377_ap_return;
reg   [63:0] ll6_V_reg_1257;
wire   [63:0] grp_my_switchEndian_fu_382_ap_return;
reg   [63:0] ll7_V_reg_1262;
wire   [63:0] grp_my_switchEndian_fu_387_ap_return;
reg   [63:0] op_V_6_reg_1267;
wire   [63:0] grp_my_switchEndian_fu_392_ap_return;
reg   [63:0] op_V_7_reg_1272;
wire   [63:0] grp_my_switchEndian_fu_397_ap_return;
reg   [63:0] op_V_8_reg_1277;
wire   [63:0] grp_my_switchEndian_fu_402_ap_return;
reg   [63:0] op_V_9_reg_1282;
wire   [63:0] op_V_10_my_switchEndian_fu_407_ap_return;
reg   [63:0] op_V_10_reg_1287;
wire   [34:0] trunc_ln155_fu_730_p1;
reg   [34:0] trunc_ln155_reg_1292;
wire   [4:0] grp_fu_433_p4;
reg   [4:0] tmp_len_V_3_reg_1297;
wire   [7:0] total_len_V_fu_737_p2;
reg   [7:0] total_len_V_reg_1302;
wire    ap_CS_fsm_state4;
wire   [515:0] tmp_4_fu_777_p6;
reg   [515:0] tmp_4_reg_1307;
wire   [519:0] p_Result_6_fu_820_p5;
reg   [519:0] p_Result_6_reg_1315;
wire   [5:0] Hi_fu_845_p2;
reg   [5:0] Hi_reg_1320;
wire   [5:0] Lo_fu_851_p2;
reg   [5:0] Lo_reg_1325;
wire   [0:0] icmp_ln414_fu_857_p2;
reg   [0:0] icmp_ln414_reg_1330;
wire   [124:0] total_len_V_3_fu_875_p2;
reg   [124:0] total_len_V_3_reg_1338;
wire   [519:0] p_Result_8_fu_995_p5;
wire   [0:0] icmp_ln1065_3_fu_1027_p2;
reg   [0:0] icmp_ln1065_3_reg_1352;
wire   [0:0] icmp_ln1065_4_fu_1043_p2;
reg   [0:0] icmp_ln1065_4_reg_1357;
wire   [63:0] ll0_V_fu_1110_p1;
reg   [63:0] ll0_V_reg_1362;
wire    ap_CS_fsm_state9;
wire   [63:0] grp_fu_443_p4;
reg   [63:0] ll1_V_reg_1367;
wire   [63:0] grp_fu_452_p4;
reg   [63:0] ll2_V_reg_1372;
wire   [63:0] grp_fu_461_p4;
reg   [63:0] ll3_V_reg_1377;
wire   [63:0] grp_fu_470_p4;
reg   [63:0] ll4_V_reg_1382;
wire   [63:0] grp_fu_479_p4;
reg   [63:0] ll5_V_3_reg_1387;
wire    grp_my_switchEndian_fu_377_ap_ready;
reg   [63:0] grp_my_switchEndian_fu_377_l;
wire    grp_my_switchEndian_fu_382_ap_ready;
reg   [63:0] grp_my_switchEndian_fu_382_l;
wire    grp_my_switchEndian_fu_387_ap_ready;
reg   [63:0] grp_my_switchEndian_fu_387_l;
wire    grp_my_switchEndian_fu_392_ap_ready;
reg   [63:0] grp_my_switchEndian_fu_392_l;
wire    grp_my_switchEndian_fu_397_ap_ready;
reg   [63:0] grp_my_switchEndian_fu_397_l;
wire    grp_my_switchEndian_fu_402_ap_ready;
reg   [63:0] grp_my_switchEndian_fu_402_l;
wire    op_V_10_my_switchEndian_fu_407_ap_ready;
reg   [63:0] op_V_10_my_switchEndian_fu_407_l;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_done;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_idle;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_ready;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_len_strm2_read;
wire   [519:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_din;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_write;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_msg_key_strm1_read;
wire   [383:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_bigHUH_V_out;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_bigHUH_V_out_ap_vld;
wire   [34:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_HUH_V_in_in_out;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_HUH_V_in_in_out_ap_vld;
wire   [3:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_tmp_len_V_4_out;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_tmp_len_V_4_out_ap_vld;
wire   [124:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_total_len_V_1_out;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_total_len_V_1_out_ap_vld;
wire   [3:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_counter_V_out;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_counter_V_out_ap_vld;
wire   [518:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_zext_ln878_out;
wire    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_zext_ln878_out_ap_vld;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_377_p_din1;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_382_p_din1;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_387_p_din1;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_392_p_din1;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_397_p_din1;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_402_p_din1;
wire   [63:0] grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_op_V_10_my_switchEndian_fu_407_p_din1;
reg   [519:0] bigBLOCK_V_2_reg_366;
reg    ap_block_state7;
wire   [63:0] ret_V_6_fu_566_p2;
wire   [63:0] ret_V_18_fu_1121_p2;
wire   [63:0] ret_V_7_fu_577_p2;
wire   [63:0] ret_V_19_fu_1131_p2;
wire   [63:0] ret_V_8_fu_588_p2;
wire   [63:0] trunc_ln674_fu_681_p1;
wire   [63:0] ret_V_20_fu_1141_p2;
wire   [63:0] ret_V_9_fu_599_p2;
wire   [63:0] ret_V_21_fu_1151_p2;
wire   [63:0] ret_V_10_fu_610_p2;
wire   [63:0] ret_V_22_fu_1161_p2;
wire   [63:0] ret_V_11_fu_621_p2;
wire   [63:0] ret_V_23_fu_1171_p2;
reg    grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [383:0] bigHUH_V_loc_fu_218;
reg   [124:0] total_len_V_1_loc_fu_206;
wire   [63:0] ret_V_fu_559_p2;
reg   [63:0] opad_buffer_0_preg;
wire   [63:0] ret_V_12_fu_1114_p2;
wire   [63:0] grp_fu_488_p2;
reg   [63:0] opad_buffer_1_preg;
wire   [63:0] grp_fu_495_p2;
reg   [63:0] opad_buffer_2_preg;
wire   [63:0] grp_fu_502_p2;
reg   [63:0] opad_buffer_3_preg;
wire   [63:0] grp_fu_509_p2;
reg   [63:0] opad_buffer_4_preg;
wire   [63:0] grp_fu_516_p2;
reg   [63:0] opad_buffer_5_preg;
reg   [62:0] opad_buffer_6_preg;
reg    ap_predicate_op232_write_state15;
reg    ap_block_state15;
reg   [62:0] opad_buffer_7_preg;
reg   [62:0] opad_buffer_8_preg;
reg   [62:0] opad_buffer_9_preg;
reg   [62:0] opad_buffer_10_preg;
reg   [62:0] opad_buffer_11_preg;
reg   [62:0] opad_buffer_12_preg;
reg   [62:0] opad_buffer_13_preg;
reg   [62:0] opad_buffer_14_preg;
reg   [62:0] opad_buffer_15_preg;
wire   [519:0] zext_ln414_21_fu_654_p1;
wire   [519:0] zext_ln391_1_fu_1012_p1;
wire   [519:0] p_Result_11_fu_1097_p5;
wire   [519:0] zext_ln414_29_fu_1203_p1;
wire   [63:0] ll0_V_1_fu_555_p1;
wire   [64:0] zext_ln414_5_fu_628_p1;
wire   [64:0] zext_ln414_4_fu_617_p1;
wire   [64:0] zext_ln414_3_fu_606_p1;
wire   [64:0] zext_ln414_2_fu_595_p1;
wire   [64:0] zext_ln414_1_fu_584_p1;
wire   [64:0] zext_ln414_fu_573_p1;
wire   [515:0] p_Result_5_fu_632_p8;
wire  signed [516:0] sext_ln414_fu_650_p1;
wire   [7:0] zext_ln886_fu_734_p1;
wire   [64:0] zext_ln414_12_fu_759_p1;
wire   [64:0] zext_ln414_11_fu_756_p1;
wire   [64:0] zext_ln414_10_fu_753_p1;
wire   [258:0] tmp_3_fu_762_p5;
wire   [259:0] zext_ln414_13_fu_773_p1;
wire   [64:0] zext_ln414_9_fu_750_p1;
wire   [64:0] zext_ln414_8_fu_747_p1;
wire   [64:0] zext_ln414_7_fu_744_p1;
wire   [519:0] zext_ln878_reload_cast_fu_801_p1;
wire   [64:0] zext_ln414_22_fu_816_p1;
wire   [2:0] trunc_ln1542_fu_833_p1;
wire   [5:0] shl_ln_fu_837_p3;
wire   [124:0] zext_ln886_2_fu_872_p1;
wire   [6:0] zext_ln414_23_fu_881_p1;
wire   [6:0] zext_ln414_24_fu_884_p1;
wire   [6:0] xor_ln414_fu_887_p2;
wire   [6:0] select_ln414_fu_893_p3;
wire   [6:0] select_ln414_2_fu_907_p3;
wire   [6:0] select_ln414_1_fu_900_p3;
wire   [6:0] xor_ln414_1_fu_914_p2;
wire   [63:0] zext_ln414_25_fu_920_p1;
wire   [63:0] shl_ln414_fu_932_p2;
reg   [63:0] tmp_fu_938_p4;
wire   [63:0] zext_ln414_26_fu_924_p1;
wire   [63:0] zext_ln414_27_fu_928_p1;
wire   [63:0] shl_ln414_1_fu_955_p2;
wire   [63:0] lshr_ln414_fu_961_p2;
wire   [63:0] select_ln414_3_fu_948_p3;
wire   [63:0] and_ln414_fu_967_p2;
wire   [63:0] p_Result_7_fu_973_p2;
wire   [64:0] zext_ln414_28_fu_979_p1;
wire   [65:0] p_Result_9_fu_983_p3;
wire   [389:0] zext_ln391_fu_991_p1;
wire   [4:0] tmp_8_fu_1017_p4;
wire   [4:0] tmp_6_fu_1033_p4;
wire   [63:0] L_V_fu_1049_p4;
wire   [60:0] trunc_ln674_2_fu_1062_p1;
wire   [64:0] p_Result_10_fu_1065_p4;
wire   [64:0] select_ln1135_fu_1075_p3;
wire   [64:0] L_V_2_fu_1082_p3;
wire   [64:0] zext_ln404_fu_1058_p1;
wire   [129:0] tmp_7_fu_1089_p3;
wire   [64:0] zext_ln414_19_fu_1177_p1;
wire   [64:0] zext_ln414_18_fu_1167_p1;
wire   [64:0] zext_ln414_17_fu_1157_p1;
wire   [64:0] zext_ln414_16_fu_1147_p1;
wire   [64:0] zext_ln414_15_fu_1137_p1;
wire   [64:0] zext_ln414_14_fu_1127_p1;
wire   [515:0] p_Result_s_fu_1181_p8;
wire  signed [516:0] sext_ln414_1_fu_1199_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_condition_326;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 15'd1;
#0 grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start_reg = 1'b0;
#0 opad_buffer_0_preg = 64'd0;
#0 opad_buffer_1_preg = 64'd0;
#0 opad_buffer_2_preg = 64'd0;
#0 opad_buffer_3_preg = 64'd0;
#0 opad_buffer_4_preg = 64'd0;
#0 opad_buffer_5_preg = 64'd0;
#0 opad_buffer_6_preg = 63'd0;
#0 opad_buffer_7_preg = 63'd0;
#0 opad_buffer_8_preg = 63'd0;
#0 opad_buffer_9_preg = 63'd0;
#0 opad_buffer_10_preg = 63'd0;
#0 opad_buffer_11_preg = 63'd0;
#0 opad_buffer_12_preg = 63'd0;
#0 opad_buffer_13_preg = 63'd0;
#0 opad_buffer_14_preg = 63'd0;
#0 opad_buffer_15_preg = 63'd0;
end

hmac_verify_my_switchEndian grp_my_switchEndian_fu_377(
    .ap_ready(grp_my_switchEndian_fu_377_ap_ready),
    .l(grp_my_switchEndian_fu_377_l),
    .ap_return(grp_my_switchEndian_fu_377_ap_return)
);

hmac_verify_my_switchEndian grp_my_switchEndian_fu_382(
    .ap_ready(grp_my_switchEndian_fu_382_ap_ready),
    .l(grp_my_switchEndian_fu_382_l),
    .ap_return(grp_my_switchEndian_fu_382_ap_return)
);

hmac_verify_my_switchEndian grp_my_switchEndian_fu_387(
    .ap_ready(grp_my_switchEndian_fu_387_ap_ready),
    .l(grp_my_switchEndian_fu_387_l),
    .ap_return(grp_my_switchEndian_fu_387_ap_return)
);

hmac_verify_my_switchEndian grp_my_switchEndian_fu_392(
    .ap_ready(grp_my_switchEndian_fu_392_ap_ready),
    .l(grp_my_switchEndian_fu_392_l),
    .ap_return(grp_my_switchEndian_fu_392_ap_return)
);

hmac_verify_my_switchEndian grp_my_switchEndian_fu_397(
    .ap_ready(grp_my_switchEndian_fu_397_ap_ready),
    .l(grp_my_switchEndian_fu_397_l),
    .ap_return(grp_my_switchEndian_fu_397_ap_return)
);

hmac_verify_my_switchEndian grp_my_switchEndian_fu_402(
    .ap_ready(grp_my_switchEndian_fu_402_ap_ready),
    .l(grp_my_switchEndian_fu_402_l),
    .ap_return(grp_my_switchEndian_fu_402_ap_return)
);

hmac_verify_my_switchEndian op_V_10_my_switchEndian_fu_407(
    .ap_ready(op_V_10_my_switchEndian_fu_407_ap_ready),
    .l(op_V_10_my_switchEndian_fu_407_l),
    .ap_return(op_V_10_my_switchEndian_fu_407_ap_return)
);

hmac_verify_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1 grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start),
    .ap_done(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_done),
    .ap_idle(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_idle),
    .ap_ready(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_ready),
    .len_strm2_dout(len_strm2_dout),
    .len_strm2_num_data_valid(6'd0),
    .len_strm2_fifo_cap(6'd0),
    .len_strm2_empty_n(len_strm2_empty_n),
    .len_strm2_read(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_len_strm2_read),
    .blk_strm1_din(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_din),
    .blk_strm1_num_data_valid(6'd0),
    .blk_strm1_fifo_cap(6'd0),
    .blk_strm1_full_n(blk_strm1_full_n),
    .blk_strm1_write(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_write),
    .msg_key_strm1_dout(msg_key_strm1_dout),
    .msg_key_strm1_num_data_valid(6'd0),
    .msg_key_strm1_fifo_cap(6'd0),
    .msg_key_strm1_empty_n(msg_key_strm1_empty_n),
    .msg_key_strm1_read(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_msg_key_strm1_read),
    .tmp_4(tmp_4_reg_1307),
    .tmp_10(reg_523),
    .tmp_11(trunc_ln155_reg_1292),
    .tmp_len_V_1(tmp_len_V_3_reg_1297),
    .zext_ln873(total_len_V_reg_1302),
    .bigHUH_V_out(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_bigHUH_V_out),
    .bigHUH_V_out_ap_vld(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_bigHUH_V_out_ap_vld),
    .HUH_V_in_in_out(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_HUH_V_in_in_out),
    .HUH_V_in_in_out_ap_vld(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_HUH_V_in_in_out_ap_vld),
    .tmp_len_V_4_out(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_tmp_len_V_4_out),
    .tmp_len_V_4_out_ap_vld(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_tmp_len_V_4_out_ap_vld),
    .total_len_V_1_out(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_total_len_V_1_out),
    .total_len_V_1_out_ap_vld(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_total_len_V_1_out_ap_vld),
    .counter_V_out(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_counter_V_out),
    .counter_V_out_ap_vld(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_counter_V_out_ap_vld),
    .zext_ln878_out(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_zext_ln878_out),
    .zext_ln878_out_ap_vld(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_zext_ln878_out_ap_vld),
    .grp_my_switchEndian_fu_377_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_377_p_din1),
    .grp_my_switchEndian_fu_377_p_dout0(grp_my_switchEndian_fu_377_ap_return),
    .grp_my_switchEndian_fu_377_p_ready(grp_my_switchEndian_fu_377_ap_ready),
    .grp_my_switchEndian_fu_382_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_382_p_din1),
    .grp_my_switchEndian_fu_382_p_dout0(grp_my_switchEndian_fu_382_ap_return),
    .grp_my_switchEndian_fu_382_p_ready(grp_my_switchEndian_fu_382_ap_ready),
    .grp_my_switchEndian_fu_387_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_387_p_din1),
    .grp_my_switchEndian_fu_387_p_dout0(grp_my_switchEndian_fu_387_ap_return),
    .grp_my_switchEndian_fu_387_p_ready(grp_my_switchEndian_fu_387_ap_ready),
    .grp_my_switchEndian_fu_392_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_392_p_din1),
    .grp_my_switchEndian_fu_392_p_dout0(grp_my_switchEndian_fu_392_ap_return),
    .grp_my_switchEndian_fu_392_p_ready(grp_my_switchEndian_fu_392_ap_ready),
    .grp_my_switchEndian_fu_397_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_397_p_din1),
    .grp_my_switchEndian_fu_397_p_dout0(grp_my_switchEndian_fu_397_ap_return),
    .grp_my_switchEndian_fu_397_p_ready(grp_my_switchEndian_fu_397_ap_ready),
    .grp_my_switchEndian_fu_402_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_402_p_din1),
    .grp_my_switchEndian_fu_402_p_dout0(grp_my_switchEndian_fu_402_ap_return),
    .grp_my_switchEndian_fu_402_p_ready(grp_my_switchEndian_fu_402_ap_ready),
    .op_V_10_my_switchEndian_fu_407_p_din1(grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_op_V_10_my_switchEndian_fu_407_p_din1),
    .op_V_10_my_switchEndian_fu_407_p_dout0(op_V_10_my_switchEndian_fu_407_ap_return),
    .op_V_10_my_switchEndian_fu_407_p_ready(op_V_10_my_switchEndian_fu_407_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start_reg <= 1'b1;
        end else if ((grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_ready == 1'b1)) begin
            grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opad_buffer_0_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            opad_buffer_0_preg <= ret_V_12_fu_1114_p2;
        end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            opad_buffer_0_preg <= ret_V_fu_559_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_10_preg[2] <= 1'b0;
        opad_buffer_10_preg[3] <= 1'b0;
        opad_buffer_10_preg[4] <= 1'b0;
        opad_buffer_10_preg[6] <= 1'b0;
        opad_buffer_10_preg[10] <= 1'b0;
        opad_buffer_10_preg[11] <= 1'b0;
        opad_buffer_10_preg[12] <= 1'b0;
        opad_buffer_10_preg[14] <= 1'b0;
        opad_buffer_10_preg[18] <= 1'b0;
        opad_buffer_10_preg[19] <= 1'b0;
        opad_buffer_10_preg[20] <= 1'b0;
        opad_buffer_10_preg[22] <= 1'b0;
        opad_buffer_10_preg[26] <= 1'b0;
        opad_buffer_10_preg[27] <= 1'b0;
        opad_buffer_10_preg[28] <= 1'b0;
        opad_buffer_10_preg[30] <= 1'b0;
        opad_buffer_10_preg[34] <= 1'b0;
        opad_buffer_10_preg[35] <= 1'b0;
        opad_buffer_10_preg[36] <= 1'b0;
        opad_buffer_10_preg[38] <= 1'b0;
        opad_buffer_10_preg[42] <= 1'b0;
        opad_buffer_10_preg[43] <= 1'b0;
        opad_buffer_10_preg[44] <= 1'b0;
        opad_buffer_10_preg[46] <= 1'b0;
        opad_buffer_10_preg[50] <= 1'b0;
        opad_buffer_10_preg[51] <= 1'b0;
        opad_buffer_10_preg[52] <= 1'b0;
        opad_buffer_10_preg[54] <= 1'b0;
        opad_buffer_10_preg[58] <= 1'b0;
        opad_buffer_10_preg[59] <= 1'b0;
        opad_buffer_10_preg[60] <= 1'b0;
        opad_buffer_10_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_10_preg[2] <= 1'b1;
            opad_buffer_10_preg[3] <= 1'b1;
            opad_buffer_10_preg[4] <= 1'b1;
            opad_buffer_10_preg[6] <= 1'b1;
            opad_buffer_10_preg[10] <= 1'b1;
            opad_buffer_10_preg[11] <= 1'b1;
            opad_buffer_10_preg[12] <= 1'b1;
            opad_buffer_10_preg[14] <= 1'b1;
            opad_buffer_10_preg[18] <= 1'b1;
            opad_buffer_10_preg[19] <= 1'b1;
            opad_buffer_10_preg[20] <= 1'b1;
            opad_buffer_10_preg[22] <= 1'b1;
            opad_buffer_10_preg[26] <= 1'b1;
            opad_buffer_10_preg[27] <= 1'b1;
            opad_buffer_10_preg[28] <= 1'b1;
            opad_buffer_10_preg[30] <= 1'b1;
            opad_buffer_10_preg[34] <= 1'b1;
            opad_buffer_10_preg[35] <= 1'b1;
            opad_buffer_10_preg[36] <= 1'b1;
            opad_buffer_10_preg[38] <= 1'b1;
            opad_buffer_10_preg[42] <= 1'b1;
            opad_buffer_10_preg[43] <= 1'b1;
            opad_buffer_10_preg[44] <= 1'b1;
            opad_buffer_10_preg[46] <= 1'b1;
            opad_buffer_10_preg[50] <= 1'b1;
            opad_buffer_10_preg[51] <= 1'b1;
            opad_buffer_10_preg[52] <= 1'b1;
            opad_buffer_10_preg[54] <= 1'b1;
            opad_buffer_10_preg[58] <= 1'b1;
            opad_buffer_10_preg[59] <= 1'b1;
            opad_buffer_10_preg[60] <= 1'b1;
            opad_buffer_10_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_11_preg[2] <= 1'b0;
        opad_buffer_11_preg[3] <= 1'b0;
        opad_buffer_11_preg[4] <= 1'b0;
        opad_buffer_11_preg[6] <= 1'b0;
        opad_buffer_11_preg[10] <= 1'b0;
        opad_buffer_11_preg[11] <= 1'b0;
        opad_buffer_11_preg[12] <= 1'b0;
        opad_buffer_11_preg[14] <= 1'b0;
        opad_buffer_11_preg[18] <= 1'b0;
        opad_buffer_11_preg[19] <= 1'b0;
        opad_buffer_11_preg[20] <= 1'b0;
        opad_buffer_11_preg[22] <= 1'b0;
        opad_buffer_11_preg[26] <= 1'b0;
        opad_buffer_11_preg[27] <= 1'b0;
        opad_buffer_11_preg[28] <= 1'b0;
        opad_buffer_11_preg[30] <= 1'b0;
        opad_buffer_11_preg[34] <= 1'b0;
        opad_buffer_11_preg[35] <= 1'b0;
        opad_buffer_11_preg[36] <= 1'b0;
        opad_buffer_11_preg[38] <= 1'b0;
        opad_buffer_11_preg[42] <= 1'b0;
        opad_buffer_11_preg[43] <= 1'b0;
        opad_buffer_11_preg[44] <= 1'b0;
        opad_buffer_11_preg[46] <= 1'b0;
        opad_buffer_11_preg[50] <= 1'b0;
        opad_buffer_11_preg[51] <= 1'b0;
        opad_buffer_11_preg[52] <= 1'b0;
        opad_buffer_11_preg[54] <= 1'b0;
        opad_buffer_11_preg[58] <= 1'b0;
        opad_buffer_11_preg[59] <= 1'b0;
        opad_buffer_11_preg[60] <= 1'b0;
        opad_buffer_11_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_11_preg[2] <= 1'b1;
            opad_buffer_11_preg[3] <= 1'b1;
            opad_buffer_11_preg[4] <= 1'b1;
            opad_buffer_11_preg[6] <= 1'b1;
            opad_buffer_11_preg[10] <= 1'b1;
            opad_buffer_11_preg[11] <= 1'b1;
            opad_buffer_11_preg[12] <= 1'b1;
            opad_buffer_11_preg[14] <= 1'b1;
            opad_buffer_11_preg[18] <= 1'b1;
            opad_buffer_11_preg[19] <= 1'b1;
            opad_buffer_11_preg[20] <= 1'b1;
            opad_buffer_11_preg[22] <= 1'b1;
            opad_buffer_11_preg[26] <= 1'b1;
            opad_buffer_11_preg[27] <= 1'b1;
            opad_buffer_11_preg[28] <= 1'b1;
            opad_buffer_11_preg[30] <= 1'b1;
            opad_buffer_11_preg[34] <= 1'b1;
            opad_buffer_11_preg[35] <= 1'b1;
            opad_buffer_11_preg[36] <= 1'b1;
            opad_buffer_11_preg[38] <= 1'b1;
            opad_buffer_11_preg[42] <= 1'b1;
            opad_buffer_11_preg[43] <= 1'b1;
            opad_buffer_11_preg[44] <= 1'b1;
            opad_buffer_11_preg[46] <= 1'b1;
            opad_buffer_11_preg[50] <= 1'b1;
            opad_buffer_11_preg[51] <= 1'b1;
            opad_buffer_11_preg[52] <= 1'b1;
            opad_buffer_11_preg[54] <= 1'b1;
            opad_buffer_11_preg[58] <= 1'b1;
            opad_buffer_11_preg[59] <= 1'b1;
            opad_buffer_11_preg[60] <= 1'b1;
            opad_buffer_11_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_12_preg[2] <= 1'b0;
        opad_buffer_12_preg[3] <= 1'b0;
        opad_buffer_12_preg[4] <= 1'b0;
        opad_buffer_12_preg[6] <= 1'b0;
        opad_buffer_12_preg[10] <= 1'b0;
        opad_buffer_12_preg[11] <= 1'b0;
        opad_buffer_12_preg[12] <= 1'b0;
        opad_buffer_12_preg[14] <= 1'b0;
        opad_buffer_12_preg[18] <= 1'b0;
        opad_buffer_12_preg[19] <= 1'b0;
        opad_buffer_12_preg[20] <= 1'b0;
        opad_buffer_12_preg[22] <= 1'b0;
        opad_buffer_12_preg[26] <= 1'b0;
        opad_buffer_12_preg[27] <= 1'b0;
        opad_buffer_12_preg[28] <= 1'b0;
        opad_buffer_12_preg[30] <= 1'b0;
        opad_buffer_12_preg[34] <= 1'b0;
        opad_buffer_12_preg[35] <= 1'b0;
        opad_buffer_12_preg[36] <= 1'b0;
        opad_buffer_12_preg[38] <= 1'b0;
        opad_buffer_12_preg[42] <= 1'b0;
        opad_buffer_12_preg[43] <= 1'b0;
        opad_buffer_12_preg[44] <= 1'b0;
        opad_buffer_12_preg[46] <= 1'b0;
        opad_buffer_12_preg[50] <= 1'b0;
        opad_buffer_12_preg[51] <= 1'b0;
        opad_buffer_12_preg[52] <= 1'b0;
        opad_buffer_12_preg[54] <= 1'b0;
        opad_buffer_12_preg[58] <= 1'b0;
        opad_buffer_12_preg[59] <= 1'b0;
        opad_buffer_12_preg[60] <= 1'b0;
        opad_buffer_12_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_12_preg[2] <= 1'b1;
            opad_buffer_12_preg[3] <= 1'b1;
            opad_buffer_12_preg[4] <= 1'b1;
            opad_buffer_12_preg[6] <= 1'b1;
            opad_buffer_12_preg[10] <= 1'b1;
            opad_buffer_12_preg[11] <= 1'b1;
            opad_buffer_12_preg[12] <= 1'b1;
            opad_buffer_12_preg[14] <= 1'b1;
            opad_buffer_12_preg[18] <= 1'b1;
            opad_buffer_12_preg[19] <= 1'b1;
            opad_buffer_12_preg[20] <= 1'b1;
            opad_buffer_12_preg[22] <= 1'b1;
            opad_buffer_12_preg[26] <= 1'b1;
            opad_buffer_12_preg[27] <= 1'b1;
            opad_buffer_12_preg[28] <= 1'b1;
            opad_buffer_12_preg[30] <= 1'b1;
            opad_buffer_12_preg[34] <= 1'b1;
            opad_buffer_12_preg[35] <= 1'b1;
            opad_buffer_12_preg[36] <= 1'b1;
            opad_buffer_12_preg[38] <= 1'b1;
            opad_buffer_12_preg[42] <= 1'b1;
            opad_buffer_12_preg[43] <= 1'b1;
            opad_buffer_12_preg[44] <= 1'b1;
            opad_buffer_12_preg[46] <= 1'b1;
            opad_buffer_12_preg[50] <= 1'b1;
            opad_buffer_12_preg[51] <= 1'b1;
            opad_buffer_12_preg[52] <= 1'b1;
            opad_buffer_12_preg[54] <= 1'b1;
            opad_buffer_12_preg[58] <= 1'b1;
            opad_buffer_12_preg[59] <= 1'b1;
            opad_buffer_12_preg[60] <= 1'b1;
            opad_buffer_12_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_13_preg[2] <= 1'b0;
        opad_buffer_13_preg[3] <= 1'b0;
        opad_buffer_13_preg[4] <= 1'b0;
        opad_buffer_13_preg[6] <= 1'b0;
        opad_buffer_13_preg[10] <= 1'b0;
        opad_buffer_13_preg[11] <= 1'b0;
        opad_buffer_13_preg[12] <= 1'b0;
        opad_buffer_13_preg[14] <= 1'b0;
        opad_buffer_13_preg[18] <= 1'b0;
        opad_buffer_13_preg[19] <= 1'b0;
        opad_buffer_13_preg[20] <= 1'b0;
        opad_buffer_13_preg[22] <= 1'b0;
        opad_buffer_13_preg[26] <= 1'b0;
        opad_buffer_13_preg[27] <= 1'b0;
        opad_buffer_13_preg[28] <= 1'b0;
        opad_buffer_13_preg[30] <= 1'b0;
        opad_buffer_13_preg[34] <= 1'b0;
        opad_buffer_13_preg[35] <= 1'b0;
        opad_buffer_13_preg[36] <= 1'b0;
        opad_buffer_13_preg[38] <= 1'b0;
        opad_buffer_13_preg[42] <= 1'b0;
        opad_buffer_13_preg[43] <= 1'b0;
        opad_buffer_13_preg[44] <= 1'b0;
        opad_buffer_13_preg[46] <= 1'b0;
        opad_buffer_13_preg[50] <= 1'b0;
        opad_buffer_13_preg[51] <= 1'b0;
        opad_buffer_13_preg[52] <= 1'b0;
        opad_buffer_13_preg[54] <= 1'b0;
        opad_buffer_13_preg[58] <= 1'b0;
        opad_buffer_13_preg[59] <= 1'b0;
        opad_buffer_13_preg[60] <= 1'b0;
        opad_buffer_13_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_13_preg[2] <= 1'b1;
            opad_buffer_13_preg[3] <= 1'b1;
            opad_buffer_13_preg[4] <= 1'b1;
            opad_buffer_13_preg[6] <= 1'b1;
            opad_buffer_13_preg[10] <= 1'b1;
            opad_buffer_13_preg[11] <= 1'b1;
            opad_buffer_13_preg[12] <= 1'b1;
            opad_buffer_13_preg[14] <= 1'b1;
            opad_buffer_13_preg[18] <= 1'b1;
            opad_buffer_13_preg[19] <= 1'b1;
            opad_buffer_13_preg[20] <= 1'b1;
            opad_buffer_13_preg[22] <= 1'b1;
            opad_buffer_13_preg[26] <= 1'b1;
            opad_buffer_13_preg[27] <= 1'b1;
            opad_buffer_13_preg[28] <= 1'b1;
            opad_buffer_13_preg[30] <= 1'b1;
            opad_buffer_13_preg[34] <= 1'b1;
            opad_buffer_13_preg[35] <= 1'b1;
            opad_buffer_13_preg[36] <= 1'b1;
            opad_buffer_13_preg[38] <= 1'b1;
            opad_buffer_13_preg[42] <= 1'b1;
            opad_buffer_13_preg[43] <= 1'b1;
            opad_buffer_13_preg[44] <= 1'b1;
            opad_buffer_13_preg[46] <= 1'b1;
            opad_buffer_13_preg[50] <= 1'b1;
            opad_buffer_13_preg[51] <= 1'b1;
            opad_buffer_13_preg[52] <= 1'b1;
            opad_buffer_13_preg[54] <= 1'b1;
            opad_buffer_13_preg[58] <= 1'b1;
            opad_buffer_13_preg[59] <= 1'b1;
            opad_buffer_13_preg[60] <= 1'b1;
            opad_buffer_13_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_14_preg[2] <= 1'b0;
        opad_buffer_14_preg[3] <= 1'b0;
        opad_buffer_14_preg[4] <= 1'b0;
        opad_buffer_14_preg[6] <= 1'b0;
        opad_buffer_14_preg[10] <= 1'b0;
        opad_buffer_14_preg[11] <= 1'b0;
        opad_buffer_14_preg[12] <= 1'b0;
        opad_buffer_14_preg[14] <= 1'b0;
        opad_buffer_14_preg[18] <= 1'b0;
        opad_buffer_14_preg[19] <= 1'b0;
        opad_buffer_14_preg[20] <= 1'b0;
        opad_buffer_14_preg[22] <= 1'b0;
        opad_buffer_14_preg[26] <= 1'b0;
        opad_buffer_14_preg[27] <= 1'b0;
        opad_buffer_14_preg[28] <= 1'b0;
        opad_buffer_14_preg[30] <= 1'b0;
        opad_buffer_14_preg[34] <= 1'b0;
        opad_buffer_14_preg[35] <= 1'b0;
        opad_buffer_14_preg[36] <= 1'b0;
        opad_buffer_14_preg[38] <= 1'b0;
        opad_buffer_14_preg[42] <= 1'b0;
        opad_buffer_14_preg[43] <= 1'b0;
        opad_buffer_14_preg[44] <= 1'b0;
        opad_buffer_14_preg[46] <= 1'b0;
        opad_buffer_14_preg[50] <= 1'b0;
        opad_buffer_14_preg[51] <= 1'b0;
        opad_buffer_14_preg[52] <= 1'b0;
        opad_buffer_14_preg[54] <= 1'b0;
        opad_buffer_14_preg[58] <= 1'b0;
        opad_buffer_14_preg[59] <= 1'b0;
        opad_buffer_14_preg[60] <= 1'b0;
        opad_buffer_14_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_14_preg[2] <= 1'b1;
            opad_buffer_14_preg[3] <= 1'b1;
            opad_buffer_14_preg[4] <= 1'b1;
            opad_buffer_14_preg[6] <= 1'b1;
            opad_buffer_14_preg[10] <= 1'b1;
            opad_buffer_14_preg[11] <= 1'b1;
            opad_buffer_14_preg[12] <= 1'b1;
            opad_buffer_14_preg[14] <= 1'b1;
            opad_buffer_14_preg[18] <= 1'b1;
            opad_buffer_14_preg[19] <= 1'b1;
            opad_buffer_14_preg[20] <= 1'b1;
            opad_buffer_14_preg[22] <= 1'b1;
            opad_buffer_14_preg[26] <= 1'b1;
            opad_buffer_14_preg[27] <= 1'b1;
            opad_buffer_14_preg[28] <= 1'b1;
            opad_buffer_14_preg[30] <= 1'b1;
            opad_buffer_14_preg[34] <= 1'b1;
            opad_buffer_14_preg[35] <= 1'b1;
            opad_buffer_14_preg[36] <= 1'b1;
            opad_buffer_14_preg[38] <= 1'b1;
            opad_buffer_14_preg[42] <= 1'b1;
            opad_buffer_14_preg[43] <= 1'b1;
            opad_buffer_14_preg[44] <= 1'b1;
            opad_buffer_14_preg[46] <= 1'b1;
            opad_buffer_14_preg[50] <= 1'b1;
            opad_buffer_14_preg[51] <= 1'b1;
            opad_buffer_14_preg[52] <= 1'b1;
            opad_buffer_14_preg[54] <= 1'b1;
            opad_buffer_14_preg[58] <= 1'b1;
            opad_buffer_14_preg[59] <= 1'b1;
            opad_buffer_14_preg[60] <= 1'b1;
            opad_buffer_14_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_15_preg[2] <= 1'b0;
        opad_buffer_15_preg[3] <= 1'b0;
        opad_buffer_15_preg[4] <= 1'b0;
        opad_buffer_15_preg[6] <= 1'b0;
        opad_buffer_15_preg[10] <= 1'b0;
        opad_buffer_15_preg[11] <= 1'b0;
        opad_buffer_15_preg[12] <= 1'b0;
        opad_buffer_15_preg[14] <= 1'b0;
        opad_buffer_15_preg[18] <= 1'b0;
        opad_buffer_15_preg[19] <= 1'b0;
        opad_buffer_15_preg[20] <= 1'b0;
        opad_buffer_15_preg[22] <= 1'b0;
        opad_buffer_15_preg[26] <= 1'b0;
        opad_buffer_15_preg[27] <= 1'b0;
        opad_buffer_15_preg[28] <= 1'b0;
        opad_buffer_15_preg[30] <= 1'b0;
        opad_buffer_15_preg[34] <= 1'b0;
        opad_buffer_15_preg[35] <= 1'b0;
        opad_buffer_15_preg[36] <= 1'b0;
        opad_buffer_15_preg[38] <= 1'b0;
        opad_buffer_15_preg[42] <= 1'b0;
        opad_buffer_15_preg[43] <= 1'b0;
        opad_buffer_15_preg[44] <= 1'b0;
        opad_buffer_15_preg[46] <= 1'b0;
        opad_buffer_15_preg[50] <= 1'b0;
        opad_buffer_15_preg[51] <= 1'b0;
        opad_buffer_15_preg[52] <= 1'b0;
        opad_buffer_15_preg[54] <= 1'b0;
        opad_buffer_15_preg[58] <= 1'b0;
        opad_buffer_15_preg[59] <= 1'b0;
        opad_buffer_15_preg[60] <= 1'b0;
        opad_buffer_15_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_15_preg[2] <= 1'b1;
            opad_buffer_15_preg[3] <= 1'b1;
            opad_buffer_15_preg[4] <= 1'b1;
            opad_buffer_15_preg[6] <= 1'b1;
            opad_buffer_15_preg[10] <= 1'b1;
            opad_buffer_15_preg[11] <= 1'b1;
            opad_buffer_15_preg[12] <= 1'b1;
            opad_buffer_15_preg[14] <= 1'b1;
            opad_buffer_15_preg[18] <= 1'b1;
            opad_buffer_15_preg[19] <= 1'b1;
            opad_buffer_15_preg[20] <= 1'b1;
            opad_buffer_15_preg[22] <= 1'b1;
            opad_buffer_15_preg[26] <= 1'b1;
            opad_buffer_15_preg[27] <= 1'b1;
            opad_buffer_15_preg[28] <= 1'b1;
            opad_buffer_15_preg[30] <= 1'b1;
            opad_buffer_15_preg[34] <= 1'b1;
            opad_buffer_15_preg[35] <= 1'b1;
            opad_buffer_15_preg[36] <= 1'b1;
            opad_buffer_15_preg[38] <= 1'b1;
            opad_buffer_15_preg[42] <= 1'b1;
            opad_buffer_15_preg[43] <= 1'b1;
            opad_buffer_15_preg[44] <= 1'b1;
            opad_buffer_15_preg[46] <= 1'b1;
            opad_buffer_15_preg[50] <= 1'b1;
            opad_buffer_15_preg[51] <= 1'b1;
            opad_buffer_15_preg[52] <= 1'b1;
            opad_buffer_15_preg[54] <= 1'b1;
            opad_buffer_15_preg[58] <= 1'b1;
            opad_buffer_15_preg[59] <= 1'b1;
            opad_buffer_15_preg[60] <= 1'b1;
            opad_buffer_15_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opad_buffer_1_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
            opad_buffer_1_preg <= grp_fu_488_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opad_buffer_2_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
            opad_buffer_2_preg <= grp_fu_495_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opad_buffer_3_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
            opad_buffer_3_preg <= grp_fu_502_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opad_buffer_4_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
            opad_buffer_4_preg <= grp_fu_509_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opad_buffer_5_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
            opad_buffer_5_preg <= grp_fu_516_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_6_preg[2] <= 1'b0;
        opad_buffer_6_preg[3] <= 1'b0;
        opad_buffer_6_preg[4] <= 1'b0;
        opad_buffer_6_preg[6] <= 1'b0;
        opad_buffer_6_preg[10] <= 1'b0;
        opad_buffer_6_preg[11] <= 1'b0;
        opad_buffer_6_preg[12] <= 1'b0;
        opad_buffer_6_preg[14] <= 1'b0;
        opad_buffer_6_preg[18] <= 1'b0;
        opad_buffer_6_preg[19] <= 1'b0;
        opad_buffer_6_preg[20] <= 1'b0;
        opad_buffer_6_preg[22] <= 1'b0;
        opad_buffer_6_preg[26] <= 1'b0;
        opad_buffer_6_preg[27] <= 1'b0;
        opad_buffer_6_preg[28] <= 1'b0;
        opad_buffer_6_preg[30] <= 1'b0;
        opad_buffer_6_preg[34] <= 1'b0;
        opad_buffer_6_preg[35] <= 1'b0;
        opad_buffer_6_preg[36] <= 1'b0;
        opad_buffer_6_preg[38] <= 1'b0;
        opad_buffer_6_preg[42] <= 1'b0;
        opad_buffer_6_preg[43] <= 1'b0;
        opad_buffer_6_preg[44] <= 1'b0;
        opad_buffer_6_preg[46] <= 1'b0;
        opad_buffer_6_preg[50] <= 1'b0;
        opad_buffer_6_preg[51] <= 1'b0;
        opad_buffer_6_preg[52] <= 1'b0;
        opad_buffer_6_preg[54] <= 1'b0;
        opad_buffer_6_preg[58] <= 1'b0;
        opad_buffer_6_preg[59] <= 1'b0;
        opad_buffer_6_preg[60] <= 1'b0;
        opad_buffer_6_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_6_preg[2] <= 1'b1;
            opad_buffer_6_preg[3] <= 1'b1;
            opad_buffer_6_preg[4] <= 1'b1;
            opad_buffer_6_preg[6] <= 1'b1;
            opad_buffer_6_preg[10] <= 1'b1;
            opad_buffer_6_preg[11] <= 1'b1;
            opad_buffer_6_preg[12] <= 1'b1;
            opad_buffer_6_preg[14] <= 1'b1;
            opad_buffer_6_preg[18] <= 1'b1;
            opad_buffer_6_preg[19] <= 1'b1;
            opad_buffer_6_preg[20] <= 1'b1;
            opad_buffer_6_preg[22] <= 1'b1;
            opad_buffer_6_preg[26] <= 1'b1;
            opad_buffer_6_preg[27] <= 1'b1;
            opad_buffer_6_preg[28] <= 1'b1;
            opad_buffer_6_preg[30] <= 1'b1;
            opad_buffer_6_preg[34] <= 1'b1;
            opad_buffer_6_preg[35] <= 1'b1;
            opad_buffer_6_preg[36] <= 1'b1;
            opad_buffer_6_preg[38] <= 1'b1;
            opad_buffer_6_preg[42] <= 1'b1;
            opad_buffer_6_preg[43] <= 1'b1;
            opad_buffer_6_preg[44] <= 1'b1;
            opad_buffer_6_preg[46] <= 1'b1;
            opad_buffer_6_preg[50] <= 1'b1;
            opad_buffer_6_preg[51] <= 1'b1;
            opad_buffer_6_preg[52] <= 1'b1;
            opad_buffer_6_preg[54] <= 1'b1;
            opad_buffer_6_preg[58] <= 1'b1;
            opad_buffer_6_preg[59] <= 1'b1;
            opad_buffer_6_preg[60] <= 1'b1;
            opad_buffer_6_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_7_preg[2] <= 1'b0;
        opad_buffer_7_preg[3] <= 1'b0;
        opad_buffer_7_preg[4] <= 1'b0;
        opad_buffer_7_preg[6] <= 1'b0;
        opad_buffer_7_preg[10] <= 1'b0;
        opad_buffer_7_preg[11] <= 1'b0;
        opad_buffer_7_preg[12] <= 1'b0;
        opad_buffer_7_preg[14] <= 1'b0;
        opad_buffer_7_preg[18] <= 1'b0;
        opad_buffer_7_preg[19] <= 1'b0;
        opad_buffer_7_preg[20] <= 1'b0;
        opad_buffer_7_preg[22] <= 1'b0;
        opad_buffer_7_preg[26] <= 1'b0;
        opad_buffer_7_preg[27] <= 1'b0;
        opad_buffer_7_preg[28] <= 1'b0;
        opad_buffer_7_preg[30] <= 1'b0;
        opad_buffer_7_preg[34] <= 1'b0;
        opad_buffer_7_preg[35] <= 1'b0;
        opad_buffer_7_preg[36] <= 1'b0;
        opad_buffer_7_preg[38] <= 1'b0;
        opad_buffer_7_preg[42] <= 1'b0;
        opad_buffer_7_preg[43] <= 1'b0;
        opad_buffer_7_preg[44] <= 1'b0;
        opad_buffer_7_preg[46] <= 1'b0;
        opad_buffer_7_preg[50] <= 1'b0;
        opad_buffer_7_preg[51] <= 1'b0;
        opad_buffer_7_preg[52] <= 1'b0;
        opad_buffer_7_preg[54] <= 1'b0;
        opad_buffer_7_preg[58] <= 1'b0;
        opad_buffer_7_preg[59] <= 1'b0;
        opad_buffer_7_preg[60] <= 1'b0;
        opad_buffer_7_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_7_preg[2] <= 1'b1;
            opad_buffer_7_preg[3] <= 1'b1;
            opad_buffer_7_preg[4] <= 1'b1;
            opad_buffer_7_preg[6] <= 1'b1;
            opad_buffer_7_preg[10] <= 1'b1;
            opad_buffer_7_preg[11] <= 1'b1;
            opad_buffer_7_preg[12] <= 1'b1;
            opad_buffer_7_preg[14] <= 1'b1;
            opad_buffer_7_preg[18] <= 1'b1;
            opad_buffer_7_preg[19] <= 1'b1;
            opad_buffer_7_preg[20] <= 1'b1;
            opad_buffer_7_preg[22] <= 1'b1;
            opad_buffer_7_preg[26] <= 1'b1;
            opad_buffer_7_preg[27] <= 1'b1;
            opad_buffer_7_preg[28] <= 1'b1;
            opad_buffer_7_preg[30] <= 1'b1;
            opad_buffer_7_preg[34] <= 1'b1;
            opad_buffer_7_preg[35] <= 1'b1;
            opad_buffer_7_preg[36] <= 1'b1;
            opad_buffer_7_preg[38] <= 1'b1;
            opad_buffer_7_preg[42] <= 1'b1;
            opad_buffer_7_preg[43] <= 1'b1;
            opad_buffer_7_preg[44] <= 1'b1;
            opad_buffer_7_preg[46] <= 1'b1;
            opad_buffer_7_preg[50] <= 1'b1;
            opad_buffer_7_preg[51] <= 1'b1;
            opad_buffer_7_preg[52] <= 1'b1;
            opad_buffer_7_preg[54] <= 1'b1;
            opad_buffer_7_preg[58] <= 1'b1;
            opad_buffer_7_preg[59] <= 1'b1;
            opad_buffer_7_preg[60] <= 1'b1;
            opad_buffer_7_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_8_preg[2] <= 1'b0;
        opad_buffer_8_preg[3] <= 1'b0;
        opad_buffer_8_preg[4] <= 1'b0;
        opad_buffer_8_preg[6] <= 1'b0;
        opad_buffer_8_preg[10] <= 1'b0;
        opad_buffer_8_preg[11] <= 1'b0;
        opad_buffer_8_preg[12] <= 1'b0;
        opad_buffer_8_preg[14] <= 1'b0;
        opad_buffer_8_preg[18] <= 1'b0;
        opad_buffer_8_preg[19] <= 1'b0;
        opad_buffer_8_preg[20] <= 1'b0;
        opad_buffer_8_preg[22] <= 1'b0;
        opad_buffer_8_preg[26] <= 1'b0;
        opad_buffer_8_preg[27] <= 1'b0;
        opad_buffer_8_preg[28] <= 1'b0;
        opad_buffer_8_preg[30] <= 1'b0;
        opad_buffer_8_preg[34] <= 1'b0;
        opad_buffer_8_preg[35] <= 1'b0;
        opad_buffer_8_preg[36] <= 1'b0;
        opad_buffer_8_preg[38] <= 1'b0;
        opad_buffer_8_preg[42] <= 1'b0;
        opad_buffer_8_preg[43] <= 1'b0;
        opad_buffer_8_preg[44] <= 1'b0;
        opad_buffer_8_preg[46] <= 1'b0;
        opad_buffer_8_preg[50] <= 1'b0;
        opad_buffer_8_preg[51] <= 1'b0;
        opad_buffer_8_preg[52] <= 1'b0;
        opad_buffer_8_preg[54] <= 1'b0;
        opad_buffer_8_preg[58] <= 1'b0;
        opad_buffer_8_preg[59] <= 1'b0;
        opad_buffer_8_preg[60] <= 1'b0;
        opad_buffer_8_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_8_preg[2] <= 1'b1;
            opad_buffer_8_preg[3] <= 1'b1;
            opad_buffer_8_preg[4] <= 1'b1;
            opad_buffer_8_preg[6] <= 1'b1;
            opad_buffer_8_preg[10] <= 1'b1;
            opad_buffer_8_preg[11] <= 1'b1;
            opad_buffer_8_preg[12] <= 1'b1;
            opad_buffer_8_preg[14] <= 1'b1;
            opad_buffer_8_preg[18] <= 1'b1;
            opad_buffer_8_preg[19] <= 1'b1;
            opad_buffer_8_preg[20] <= 1'b1;
            opad_buffer_8_preg[22] <= 1'b1;
            opad_buffer_8_preg[26] <= 1'b1;
            opad_buffer_8_preg[27] <= 1'b1;
            opad_buffer_8_preg[28] <= 1'b1;
            opad_buffer_8_preg[30] <= 1'b1;
            opad_buffer_8_preg[34] <= 1'b1;
            opad_buffer_8_preg[35] <= 1'b1;
            opad_buffer_8_preg[36] <= 1'b1;
            opad_buffer_8_preg[38] <= 1'b1;
            opad_buffer_8_preg[42] <= 1'b1;
            opad_buffer_8_preg[43] <= 1'b1;
            opad_buffer_8_preg[44] <= 1'b1;
            opad_buffer_8_preg[46] <= 1'b1;
            opad_buffer_8_preg[50] <= 1'b1;
            opad_buffer_8_preg[51] <= 1'b1;
            opad_buffer_8_preg[52] <= 1'b1;
            opad_buffer_8_preg[54] <= 1'b1;
            opad_buffer_8_preg[58] <= 1'b1;
            opad_buffer_8_preg[59] <= 1'b1;
            opad_buffer_8_preg[60] <= 1'b1;
            opad_buffer_8_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                opad_buffer_9_preg[2] <= 1'b0;
        opad_buffer_9_preg[3] <= 1'b0;
        opad_buffer_9_preg[4] <= 1'b0;
        opad_buffer_9_preg[6] <= 1'b0;
        opad_buffer_9_preg[10] <= 1'b0;
        opad_buffer_9_preg[11] <= 1'b0;
        opad_buffer_9_preg[12] <= 1'b0;
        opad_buffer_9_preg[14] <= 1'b0;
        opad_buffer_9_preg[18] <= 1'b0;
        opad_buffer_9_preg[19] <= 1'b0;
        opad_buffer_9_preg[20] <= 1'b0;
        opad_buffer_9_preg[22] <= 1'b0;
        opad_buffer_9_preg[26] <= 1'b0;
        opad_buffer_9_preg[27] <= 1'b0;
        opad_buffer_9_preg[28] <= 1'b0;
        opad_buffer_9_preg[30] <= 1'b0;
        opad_buffer_9_preg[34] <= 1'b0;
        opad_buffer_9_preg[35] <= 1'b0;
        opad_buffer_9_preg[36] <= 1'b0;
        opad_buffer_9_preg[38] <= 1'b0;
        opad_buffer_9_preg[42] <= 1'b0;
        opad_buffer_9_preg[43] <= 1'b0;
        opad_buffer_9_preg[44] <= 1'b0;
        opad_buffer_9_preg[46] <= 1'b0;
        opad_buffer_9_preg[50] <= 1'b0;
        opad_buffer_9_preg[51] <= 1'b0;
        opad_buffer_9_preg[52] <= 1'b0;
        opad_buffer_9_preg[54] <= 1'b0;
        opad_buffer_9_preg[58] <= 1'b0;
        opad_buffer_9_preg[59] <= 1'b0;
        opad_buffer_9_preg[60] <= 1'b0;
        opad_buffer_9_preg[62] <= 1'b0;
    end else begin
        if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
                        opad_buffer_9_preg[2] <= 1'b1;
            opad_buffer_9_preg[3] <= 1'b1;
            opad_buffer_9_preg[4] <= 1'b1;
            opad_buffer_9_preg[6] <= 1'b1;
            opad_buffer_9_preg[10] <= 1'b1;
            opad_buffer_9_preg[11] <= 1'b1;
            opad_buffer_9_preg[12] <= 1'b1;
            opad_buffer_9_preg[14] <= 1'b1;
            opad_buffer_9_preg[18] <= 1'b1;
            opad_buffer_9_preg[19] <= 1'b1;
            opad_buffer_9_preg[20] <= 1'b1;
            opad_buffer_9_preg[22] <= 1'b1;
            opad_buffer_9_preg[26] <= 1'b1;
            opad_buffer_9_preg[27] <= 1'b1;
            opad_buffer_9_preg[28] <= 1'b1;
            opad_buffer_9_preg[30] <= 1'b1;
            opad_buffer_9_preg[34] <= 1'b1;
            opad_buffer_9_preg[35] <= 1'b1;
            opad_buffer_9_preg[36] <= 1'b1;
            opad_buffer_9_preg[38] <= 1'b1;
            opad_buffer_9_preg[42] <= 1'b1;
            opad_buffer_9_preg[43] <= 1'b1;
            opad_buffer_9_preg[44] <= 1'b1;
            opad_buffer_9_preg[46] <= 1'b1;
            opad_buffer_9_preg[50] <= 1'b1;
            opad_buffer_9_preg[51] <= 1'b1;
            opad_buffer_9_preg[52] <= 1'b1;
            opad_buffer_9_preg[54] <= 1'b1;
            opad_buffer_9_preg[58] <= 1'b1;
            opad_buffer_9_preg[59] <= 1'b1;
            opad_buffer_9_preg[60] <= 1'b1;
            opad_buffer_9_preg[62] <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_326)) begin
        if ((icmp_ln1065_2_fu_1006_p2 == 1'd1)) begin
            bigBLOCK_V_2_reg_366 <= p_Result_8_fu_995_p5;
        end else if ((icmp_ln1065_2_fu_1006_p2 == 1'd0)) begin
            bigBLOCK_V_2_reg_366 <= 520'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Hi_reg_1320 <= Hi_fu_845_p2;
        Lo_reg_1325[5 : 3] <= Lo_fu_851_p2[5 : 3];
        icmp_ln414_reg_1330 <= icmp_ln414_fu_857_p2;
        p_Result_6_reg_1315 <= p_Result_6_fu_820_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_bigHUH_V_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        bigHUH_V_loc_fu_218 <= grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_bigHUH_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1065_fu_543_p2 == 1'd1))) begin
        icmp_ln1065_1_reg_1253 <= icmp_ln1065_1_fu_549_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln1065_3_reg_1352 <= icmp_ln1065_3_fu_1027_p2;
        icmp_ln1065_4_reg_1357 <= icmp_ln1065_4_fu_1043_p2;
        total_len_V_3_reg_1338 <= total_len_V_3_fu_875_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1065_reg_1249 <= icmp_ln1065_fu_543_p2;
        tmp_len_V_reg_1244 <= {{len_strm2_dout[34:30]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ll0_V_reg_1362 <= ll0_V_fu_1110_p1;
        ll1_V_reg_1367 <= {{reg_523[127:64]}};
        ll2_V_reg_1372 <= {{reg_523[191:128]}};
        ll3_V_reg_1377 <= {{reg_523[255:192]}};
        ll4_V_reg_1382 <= {{reg_523[319:256]}};
        ll5_V_3_reg_1387 <= {{reg_523[383:320]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ll6_V_reg_1257 <= grp_my_switchEndian_fu_377_ap_return;
        ll7_V_reg_1262 <= grp_my_switchEndian_fu_382_ap_return;
        op_V_10_reg_1287 <= op_V_10_my_switchEndian_fu_407_ap_return;
        op_V_6_reg_1267 <= grp_my_switchEndian_fu_387_ap_return;
        op_V_7_reg_1272 <= grp_my_switchEndian_fu_392_ap_return;
        op_V_8_reg_1277 <= grp_my_switchEndian_fu_397_ap_return;
        op_V_9_reg_1282 <= grp_my_switchEndian_fu_402_ap_return;
        tmp_len_V_3_reg_1297 <= {{len_strm2_dout[29:25]}};
        trunc_ln155_reg_1292 <= trunc_ln155_fu_730_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((~((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        reg_523 <= msg_key_strm1_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_4_reg_1307[63 : 0] <= tmp_4_fu_777_p6[63 : 0];
tmp_4_reg_1307[128 : 65] <= tmp_4_fu_777_p6[128 : 65];
tmp_4_reg_1307[193 : 130] <= tmp_4_fu_777_p6[193 : 130];
tmp_4_reg_1307[258 : 195] <= tmp_4_fu_777_p6[258 : 195];
tmp_4_reg_1307[323 : 260] <= tmp_4_fu_777_p6[323 : 260];
tmp_4_reg_1307[388 : 325] <= tmp_4_fu_777_p6[388 : 325];
tmp_4_reg_1307[453 : 390] <= tmp_4_fu_777_p6[453 : 390];
        total_len_V_reg_1302 <= total_len_V_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_total_len_V_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        total_len_V_1_loc_fu_206 <= grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_total_len_V_1_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((blk_strm1_full_n == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm1_full_n == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm1_full_n == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if (((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1))) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm1_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm1_full_n == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((blk_strm1_full_n == 1'b0) & (icmp_ln1065_2_fu_1006_p2 == 1'd0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm1_full_n == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln1065_2_fu_1006_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)))) begin
        blk_strm1_blk_n = blk_strm1_full_n;
    end else begin
        blk_strm1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (ap_predicate_op232_write_state15 == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        blk_strm1_din = 520'd1716199415032652524013680470644134662398328972532356679149096292804538593064897400035392681764656244954837477002288279689545728976449635057390811738558955520;
    end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        blk_strm1_din = 520'd9223372036854775808;
    end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        blk_strm1_din = zext_ln414_29_fu_1203_p1;
    end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        blk_strm1_din = p_Result_11_fu_1097_p5;
    end else if ((~((blk_strm1_full_n == 1'b0) & (icmp_ln1065_2_fu_1006_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1065_2_fu_1006_p2 == 1'd0))) begin
        blk_strm1_din = zext_ln391_1_fu_1012_p1;
    end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        blk_strm1_din = p_Result_6_fu_820_p5;
    end else if ((((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | (~((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)))) begin
        blk_strm1_din = 520'd363430464359855808430367475123267415762081673745750234102032974440695599719878860646628315544094421737054245414135708388717971436676228211934395690103748150;
    end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        blk_strm1_din = zext_ln414_21_fu_654_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        blk_strm1_din = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_din;
    end else begin
        blk_strm1_din = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_din;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (ap_predicate_op232_write_state15 == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | (~((blk_strm1_full_n == 1'b0) & (icmp_ln1065_2_fu_1006_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1065_2_fu_1006_p2 == 1'd0)) | (~((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)))) begin
        blk_strm1_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        blk_strm1_write = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_blk_strm1_write;
    end else begin
        blk_strm1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_my_switchEndian_fu_377_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_377_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_switchEndian_fu_377_l = ret_V_18_fu_1121_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_switchEndian_fu_377_l = {{bigHUH_V_loc_fu_218[383:320]}};
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_my_switchEndian_fu_377_l = {{reg_523[447:384]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_switchEndian_fu_377_l = ret_V_6_fu_566_p2;
    end else begin
        grp_my_switchEndian_fu_377_l = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_my_switchEndian_fu_382_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_382_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_switchEndian_fu_382_l = ret_V_19_fu_1131_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_my_switchEndian_fu_382_l = {{reg_523[511:448]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_switchEndian_fu_382_l = ret_V_7_fu_577_p2;
    end else begin
        grp_my_switchEndian_fu_382_l = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_my_switchEndian_fu_387_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_387_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_switchEndian_fu_387_l = ret_V_20_fu_1141_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_my_switchEndian_fu_387_l = trunc_ln674_fu_681_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_switchEndian_fu_387_l = ret_V_8_fu_588_p2;
    end else begin
        grp_my_switchEndian_fu_387_l = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_my_switchEndian_fu_392_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_392_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_switchEndian_fu_392_l = ret_V_21_fu_1151_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_my_switchEndian_fu_392_l = {{msg_key_strm1_dout[127:64]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_switchEndian_fu_392_l = ret_V_9_fu_599_p2;
    end else begin
        grp_my_switchEndian_fu_392_l = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_my_switchEndian_fu_397_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_397_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_switchEndian_fu_397_l = ret_V_22_fu_1161_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_my_switchEndian_fu_397_l = {{msg_key_strm1_dout[191:128]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_switchEndian_fu_397_l = ret_V_10_fu_610_p2;
    end else begin
        grp_my_switchEndian_fu_397_l = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_my_switchEndian_fu_402_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_grp_my_switchEndian_fu_402_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_switchEndian_fu_402_l = ret_V_23_fu_1171_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_my_switchEndian_fu_402_l = {{msg_key_strm1_dout[255:192]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_switchEndian_fu_402_l = ret_V_11_fu_621_p2;
    end else begin
        grp_my_switchEndian_fu_402_l = 'bx;
    end
end

always @ (*) begin
    if ((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        len_strm2_blk_n = len_strm2_empty_n;
    end else begin
        len_strm2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        len_strm2_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        len_strm2_read = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_len_strm2_read;
    end else begin
        len_strm2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        msg_key_strm1_blk_n = msg_key_strm1_empty_n;
    end else begin
        msg_key_strm1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        msg_key_strm1_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        msg_key_strm1_read = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_msg_key_strm1_read;
    end else begin
        msg_key_strm1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        op_V_10_my_switchEndian_fu_407_l = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_op_V_10_my_switchEndian_fu_407_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        op_V_10_my_switchEndian_fu_407_l = {{msg_key_strm1_dout[319:256]}};
    end else begin
        op_V_10_my_switchEndian_fu_407_l = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        opad_buffer_0 = ret_V_12_fu_1114_p2;
    end else if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        opad_buffer_0 = ret_V_fu_559_p2;
    end else begin
        opad_buffer_0 = opad_buffer_0_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_1 = grp_fu_488_p2;
    end else begin
        opad_buffer_1 = opad_buffer_1_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_10 = 63'd6655295901103053916;
    end else begin
        opad_buffer_10 = opad_buffer_10_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_11 = 63'd6655295901103053916;
    end else begin
        opad_buffer_11 = opad_buffer_11_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_12 = 63'd6655295901103053916;
    end else begin
        opad_buffer_12 = opad_buffer_12_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_13 = 63'd6655295901103053916;
    end else begin
        opad_buffer_13 = opad_buffer_13_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_14 = 63'd6655295901103053916;
    end else begin
        opad_buffer_14 = opad_buffer_14_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_15 = 63'd6655295901103053916;
    end else begin
        opad_buffer_15 = opad_buffer_15_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_2 = grp_fu_495_p2;
    end else begin
        opad_buffer_2 = opad_buffer_2_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_3 = grp_fu_502_p2;
    end else begin
        opad_buffer_3 = opad_buffer_3_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_4 = grp_fu_509_p2;
    end else begin
        opad_buffer_4 = opad_buffer_4_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_5 = grp_fu_516_p2;
    end else begin
        opad_buffer_5 = opad_buffer_5_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_6 = 63'd6655295901103053916;
    end else begin
        opad_buffer_6 = opad_buffer_6_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_7 = 63'd6655295901103053916;
    end else begin
        opad_buffer_7 = opad_buffer_7_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_8 = 63'd6655295901103053916;
    end else begin
        opad_buffer_8 = opad_buffer_8_preg;
    end
end

always @ (*) begin
    if (((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1)) | ((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        opad_buffer_9 = 63'd6655295901103053916;
    end else begin
        opad_buffer_9 = opad_buffer_9_preg;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1065_1_fu_549_p2 == 1'd1) & (icmp_ln1065_fu_543_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln1065_1_fu_549_p2 == 1'd0) | (icmp_ln1065_fu_543_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((blk_strm1_full_n == 1'b0) & (icmp_ln1065_2_fu_1006_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((blk_strm1_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if ((~((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1)) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Hi_fu_845_p2 = (shl_ln_fu_837_p3 ^ 6'd63);

assign L_V_2_fu_1082_p3 = ((icmp_ln1065_3_reg_1352[0:0] == 1'b1) ? select_ln1135_fu_1075_p3 : p_Result_10_fu_1065_p4);

assign L_V_fu_1049_p4 = {{total_len_V_3_reg_1338[124:61]}};

assign Lo_fu_851_p2 = ($signed(6'd56) - $signed(shl_ln_fu_837_p3));

assign and_ln414_fu_967_p2 = (shl_ln414_1_fu_955_p2 & lshr_ln414_fu_961_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state15 = ((blk_strm1_full_n == 1'b0) & (ap_predicate_op232_write_state15 == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((blk_strm1_full_n == 1'b0) | (len_strm2_empty_n == 1'b0) | (msg_key_strm1_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((blk_strm1_full_n == 1'b0) & (icmp_ln1065_2_fu_1006_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_326 = (~((blk_strm1_full_n == 1'b0) & (icmp_ln1065_2_fu_1006_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state7));
end

always @ (*) begin
    ap_predicate_op232_write_state15 = ((icmp_ln1065_1_reg_1253 == 1'd1) & (icmp_ln1065_reg_1249 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign grp_fu_433_p4 = {{len_strm2_dout[29:25]}};

assign grp_fu_443_p4 = {{reg_523[127:64]}};

assign grp_fu_452_p4 = {{reg_523[191:128]}};

assign grp_fu_461_p4 = {{reg_523[255:192]}};

assign grp_fu_470_p4 = {{reg_523[319:256]}};

assign grp_fu_479_p4 = {{reg_523[383:320]}};

assign grp_fu_488_p2 = (grp_fu_443_p4 ^ 64'd6655295901103053916);

assign grp_fu_495_p2 = (grp_fu_452_p4 ^ 64'd6655295901103053916);

assign grp_fu_502_p2 = (grp_fu_461_p4 ^ 64'd6655295901103053916);

assign grp_fu_509_p2 = (grp_fu_470_p4 ^ 64'd6655295901103053916);

assign grp_fu_516_p2 = (grp_fu_479_p4 ^ 64'd6655295901103053916);

assign grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_ap_start_reg;

assign icmp_ln1065_1_fu_549_p2 = ((grp_fu_433_p4 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln1065_2_fu_1006_p2 = ((grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_counter_V_out == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln1065_3_fu_1027_p2 = ((tmp_8_fu_1017_p4 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln1065_4_fu_1043_p2 = ((tmp_6_fu_1033_p4 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln1065_fu_543_p2 = ((tmp_len_V_fu_533_p4 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln414_fu_857_p2 = ((Lo_fu_851_p2 > Hi_fu_845_p2) ? 1'b1 : 1'b0);

assign ll0_V_1_fu_555_p1 = reg_523[63:0];

assign ll0_V_fu_1110_p1 = reg_523[63:0];

assign lshr_ln414_fu_961_p2 = 64'd18446744073709551615 >> zext_ln414_27_fu_928_p1;

assign p_Result_10_fu_1065_p4 = {{{{1'd1}, {trunc_ln674_2_fu_1062_p1}}}, {3'd0}};

assign p_Result_11_fu_1097_p5 = {{tmp_7_fu_1089_p3}, {bigBLOCK_V_2_reg_366[389:0]}};

assign p_Result_5_fu_632_p8 = {{{{{{{{{{{{126'd59048998965692262773561577250491872822}, {zext_ln414_5_fu_628_p1}}}, {zext_ln414_4_fu_617_p1}}}, {zext_ln414_3_fu_606_p1}}}, {zext_ln414_2_fu_595_p1}}}, {zext_ln414_1_fu_584_p1}}}, {zext_ln414_fu_573_p1}};

assign p_Result_6_fu_820_p5 = {{zext_ln414_22_fu_816_p1}, {zext_ln878_reload_cast_fu_801_p1[454:0]}};

assign p_Result_7_fu_973_p2 = (select_ln414_3_fu_948_p3 & and_ln414_fu_967_p2);

assign p_Result_8_fu_995_p5 = {{p_Result_6_reg_1315[519:390]}, {zext_ln391_fu_991_p1}};

assign p_Result_9_fu_983_p3 = {{1'd0}, {zext_ln414_28_fu_979_p1}};

assign p_Result_s_fu_1181_p8 = {{{{{{{{{{{{126'd59048998965692262773561577250491872822}, {zext_ln414_19_fu_1177_p1}}}, {zext_ln414_18_fu_1167_p1}}}, {zext_ln414_17_fu_1157_p1}}}, {zext_ln414_16_fu_1147_p1}}}, {zext_ln414_15_fu_1137_p1}}}, {zext_ln414_14_fu_1127_p1}};

assign ret_V_10_fu_610_p2 = (grp_fu_470_p4 ^ 64'd3906369333256140342);

assign ret_V_11_fu_621_p2 = (grp_fu_479_p4 ^ 64'd3906369333256140342);

assign ret_V_12_fu_1114_p2 = (ll0_V_fu_1110_p1 ^ 64'd6655295901103053916);

assign ret_V_18_fu_1121_p2 = (ll0_V_reg_1362 ^ 64'd3906369333256140342);

assign ret_V_19_fu_1131_p2 = (ll1_V_reg_1367 ^ 64'd3906369333256140342);

assign ret_V_20_fu_1141_p2 = (ll2_V_reg_1372 ^ 64'd3906369333256140342);

assign ret_V_21_fu_1151_p2 = (ll3_V_reg_1377 ^ 64'd3906369333256140342);

assign ret_V_22_fu_1161_p2 = (ll4_V_reg_1382 ^ 64'd3906369333256140342);

assign ret_V_23_fu_1171_p2 = (ll5_V_3_reg_1387 ^ 64'd3906369333256140342);

assign ret_V_6_fu_566_p2 = (ll0_V_1_fu_555_p1 ^ 64'd3906369333256140342);

assign ret_V_7_fu_577_p2 = (grp_fu_443_p4 ^ 64'd3906369333256140342);

assign ret_V_8_fu_588_p2 = (grp_fu_452_p4 ^ 64'd3906369333256140342);

assign ret_V_9_fu_599_p2 = (grp_fu_461_p4 ^ 64'd3906369333256140342);

assign ret_V_fu_559_p2 = (ll0_V_1_fu_555_p1 ^ 64'd6655295901103053916);

assign select_ln1135_fu_1075_p3 = ((icmp_ln1065_4_reg_1357[0:0] == 1'b1) ? 65'd18446744073709552640 : p_Result_10_fu_1065_p4);

assign select_ln414_1_fu_900_p3 = ((icmp_ln414_reg_1330[0:0] == 1'b1) ? zext_ln414_24_fu_884_p1 : zext_ln414_23_fu_881_p1);

assign select_ln414_2_fu_907_p3 = ((icmp_ln414_reg_1330[0:0] == 1'b1) ? xor_ln414_fu_887_p2 : zext_ln414_23_fu_881_p1);

assign select_ln414_3_fu_948_p3 = ((icmp_ln414_reg_1330[0:0] == 1'b1) ? tmp_fu_938_p4 : shl_ln414_fu_932_p2);

assign select_ln414_fu_893_p3 = ((icmp_ln414_reg_1330[0:0] == 1'b1) ? zext_ln414_23_fu_881_p1 : zext_ln414_24_fu_884_p1);

assign sext_ln414_1_fu_1199_p1 = $signed(p_Result_s_fu_1181_p8);

assign sext_ln414_fu_650_p1 = $signed(p_Result_5_fu_632_p8);

assign shl_ln414_1_fu_955_p2 = 64'd18446744073709551615 << zext_ln414_26_fu_924_p1;

assign shl_ln414_fu_932_p2 = 64'd128 << zext_ln414_25_fu_920_p1;

assign shl_ln_fu_837_p3 = {{trunc_ln1542_fu_833_p1}, {3'd0}};

assign start_out = real_start;

assign tmp_3_fu_762_p5 = {{{{op_V_10_reg_1287}, {zext_ln414_12_fu_759_p1}}, {zext_ln414_11_fu_756_p1}}, {zext_ln414_10_fu_753_p1}};

assign tmp_4_fu_777_p6 = {{{{{{{{61'd1600526324042446390}, {zext_ln414_13_fu_773_p1}}}, {zext_ln414_9_fu_750_p1}}}, {zext_ln414_8_fu_747_p1}}}, {zext_ln414_7_fu_744_p1}};

assign tmp_6_fu_1033_p4 = {{grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_HUH_V_in_in_out[29:25]}};

assign tmp_7_fu_1089_p3 = {{L_V_2_fu_1082_p3}, {zext_ln404_fu_1058_p1}};

assign tmp_8_fu_1017_p4 = {{grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_HUH_V_in_in_out[34:30]}};

integer ap_tvar_int_0;

always @ (shl_ln414_fu_932_p2) begin
    for (ap_tvar_int_0 = 64 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 63 - 0) begin
            tmp_fu_938_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_fu_938_p4[ap_tvar_int_0] = shl_ln414_fu_932_p2[63 - ap_tvar_int_0];
        end
    end
end

assign tmp_len_V_fu_533_p4 = {{len_strm2_dout[34:30]}};

assign total_len_V_3_fu_875_p2 = (total_len_V_1_loc_fu_206 + zext_ln886_2_fu_872_p1);

assign total_len_V_fu_737_p2 = ($signed(zext_ln886_fu_734_p1) + $signed(8'd176));

assign trunc_ln1542_fu_833_p1 = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_tmp_len_V_4_out[2:0];

assign trunc_ln155_fu_730_p1 = len_strm2_dout[34:0];

assign trunc_ln674_2_fu_1062_p1 = total_len_V_3_reg_1338[60:0];

assign trunc_ln674_fu_681_p1 = msg_key_strm1_dout[63:0];

assign xor_ln414_1_fu_914_p2 = (select_ln414_fu_893_p3 ^ 7'd63);

assign xor_ln414_fu_887_p2 = (zext_ln414_23_fu_881_p1 ^ 7'd63);

assign zext_ln391_1_fu_1012_p1 = p_Result_9_fu_983_p3;

assign zext_ln391_fu_991_p1 = p_Result_9_fu_983_p3;

assign zext_ln404_fu_1058_p1 = L_V_fu_1049_p4;

assign zext_ln414_10_fu_753_p1 = op_V_7_reg_1272;

assign zext_ln414_11_fu_756_p1 = op_V_8_reg_1277;

assign zext_ln414_12_fu_759_p1 = op_V_9_reg_1282;

assign zext_ln414_13_fu_773_p1 = tmp_3_fu_762_p5;

assign zext_ln414_14_fu_1127_p1 = grp_my_switchEndian_fu_377_ap_return;

assign zext_ln414_15_fu_1137_p1 = grp_my_switchEndian_fu_382_ap_return;

assign zext_ln414_16_fu_1147_p1 = grp_my_switchEndian_fu_387_ap_return;

assign zext_ln414_17_fu_1157_p1 = grp_my_switchEndian_fu_392_ap_return;

assign zext_ln414_18_fu_1167_p1 = grp_my_switchEndian_fu_397_ap_return;

assign zext_ln414_19_fu_1177_p1 = grp_my_switchEndian_fu_402_ap_return;

assign zext_ln414_1_fu_584_p1 = grp_my_switchEndian_fu_382_ap_return;

assign zext_ln414_21_fu_654_p1 = $unsigned(sext_ln414_fu_650_p1);

assign zext_ln414_22_fu_816_p1 = grp_my_switchEndian_fu_377_ap_return;

assign zext_ln414_23_fu_881_p1 = Lo_reg_1325;

assign zext_ln414_24_fu_884_p1 = Hi_reg_1320;

assign zext_ln414_25_fu_920_p1 = select_ln414_2_fu_907_p3;

assign zext_ln414_26_fu_924_p1 = select_ln414_1_fu_900_p3;

assign zext_ln414_27_fu_928_p1 = xor_ln414_1_fu_914_p2;

assign zext_ln414_28_fu_979_p1 = p_Result_7_fu_973_p2;

assign zext_ln414_29_fu_1203_p1 = $unsigned(sext_ln414_1_fu_1199_p1);

assign zext_ln414_2_fu_595_p1 = grp_my_switchEndian_fu_387_ap_return;

assign zext_ln414_3_fu_606_p1 = grp_my_switchEndian_fu_392_ap_return;

assign zext_ln414_4_fu_617_p1 = grp_my_switchEndian_fu_397_ap_return;

assign zext_ln414_5_fu_628_p1 = grp_my_switchEndian_fu_402_ap_return;

assign zext_ln414_7_fu_744_p1 = ll6_V_reg_1257;

assign zext_ln414_8_fu_747_p1 = ll7_V_reg_1262;

assign zext_ln414_9_fu_750_p1 = op_V_6_reg_1267;

assign zext_ln414_fu_573_p1 = grp_my_switchEndian_fu_377_ap_return;

assign zext_ln878_reload_cast_fu_801_p1 = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_zext_ln878_out;

assign zext_ln886_2_fu_872_p1 = grp_preProcessingOneTripForHMAC23_Pipeline_VITIS_LOOP_1059_1_fu_412_tmp_len_V_4_out;

assign zext_ln886_fu_734_p1 = tmp_len_V_reg_1244;

always @ (posedge ap_clk) begin
    tmp_4_reg_1307[64] <= 1'b0;
    tmp_4_reg_1307[129:129] <= 1'b0;
    tmp_4_reg_1307[194:194] <= 1'b0;
    tmp_4_reg_1307[259:259] <= 1'b0;
    tmp_4_reg_1307[324:324] <= 1'b0;
    tmp_4_reg_1307[389:389] <= 1'b0;
    tmp_4_reg_1307[515:454] <= 62'b10110001101100011011000110110001101100011011000110110001101100;
    Lo_reg_1325[2:0] <= 3'b000;
    opad_buffer_6_preg[1:0] <= 2'b00;
    opad_buffer_6_preg[5:5] <= 1'b0;
    opad_buffer_6_preg[9:7] <= 3'b000;
    opad_buffer_6_preg[13:13] <= 1'b0;
    opad_buffer_6_preg[17:15] <= 3'b000;
    opad_buffer_6_preg[21:21] <= 1'b0;
    opad_buffer_6_preg[25:23] <= 3'b000;
    opad_buffer_6_preg[29:29] <= 1'b0;
    opad_buffer_6_preg[33:31] <= 3'b000;
    opad_buffer_6_preg[37:37] <= 1'b0;
    opad_buffer_6_preg[41:39] <= 3'b000;
    opad_buffer_6_preg[45:45] <= 1'b0;
    opad_buffer_6_preg[49:47] <= 3'b000;
    opad_buffer_6_preg[53:53] <= 1'b0;
    opad_buffer_6_preg[57:55] <= 3'b000;
    opad_buffer_6_preg[61] <= 1'b0;
    opad_buffer_7_preg[1:0] <= 2'b00;
    opad_buffer_7_preg[5:5] <= 1'b0;
    opad_buffer_7_preg[9:7] <= 3'b000;
    opad_buffer_7_preg[13:13] <= 1'b0;
    opad_buffer_7_preg[17:15] <= 3'b000;
    opad_buffer_7_preg[21:21] <= 1'b0;
    opad_buffer_7_preg[25:23] <= 3'b000;
    opad_buffer_7_preg[29:29] <= 1'b0;
    opad_buffer_7_preg[33:31] <= 3'b000;
    opad_buffer_7_preg[37:37] <= 1'b0;
    opad_buffer_7_preg[41:39] <= 3'b000;
    opad_buffer_7_preg[45:45] <= 1'b0;
    opad_buffer_7_preg[49:47] <= 3'b000;
    opad_buffer_7_preg[53:53] <= 1'b0;
    opad_buffer_7_preg[57:55] <= 3'b000;
    opad_buffer_7_preg[61] <= 1'b0;
    opad_buffer_8_preg[1:0] <= 2'b00;
    opad_buffer_8_preg[5:5] <= 1'b0;
    opad_buffer_8_preg[9:7] <= 3'b000;
    opad_buffer_8_preg[13:13] <= 1'b0;
    opad_buffer_8_preg[17:15] <= 3'b000;
    opad_buffer_8_preg[21:21] <= 1'b0;
    opad_buffer_8_preg[25:23] <= 3'b000;
    opad_buffer_8_preg[29:29] <= 1'b0;
    opad_buffer_8_preg[33:31] <= 3'b000;
    opad_buffer_8_preg[37:37] <= 1'b0;
    opad_buffer_8_preg[41:39] <= 3'b000;
    opad_buffer_8_preg[45:45] <= 1'b0;
    opad_buffer_8_preg[49:47] <= 3'b000;
    opad_buffer_8_preg[53:53] <= 1'b0;
    opad_buffer_8_preg[57:55] <= 3'b000;
    opad_buffer_8_preg[61] <= 1'b0;
    opad_buffer_9_preg[1:0] <= 2'b00;
    opad_buffer_9_preg[5:5] <= 1'b0;
    opad_buffer_9_preg[9:7] <= 3'b000;
    opad_buffer_9_preg[13:13] <= 1'b0;
    opad_buffer_9_preg[17:15] <= 3'b000;
    opad_buffer_9_preg[21:21] <= 1'b0;
    opad_buffer_9_preg[25:23] <= 3'b000;
    opad_buffer_9_preg[29:29] <= 1'b0;
    opad_buffer_9_preg[33:31] <= 3'b000;
    opad_buffer_9_preg[37:37] <= 1'b0;
    opad_buffer_9_preg[41:39] <= 3'b000;
    opad_buffer_9_preg[45:45] <= 1'b0;
    opad_buffer_9_preg[49:47] <= 3'b000;
    opad_buffer_9_preg[53:53] <= 1'b0;
    opad_buffer_9_preg[57:55] <= 3'b000;
    opad_buffer_9_preg[61] <= 1'b0;
    opad_buffer_10_preg[1:0] <= 2'b00;
    opad_buffer_10_preg[5:5] <= 1'b0;
    opad_buffer_10_preg[9:7] <= 3'b000;
    opad_buffer_10_preg[13:13] <= 1'b0;
    opad_buffer_10_preg[17:15] <= 3'b000;
    opad_buffer_10_preg[21:21] <= 1'b0;
    opad_buffer_10_preg[25:23] <= 3'b000;
    opad_buffer_10_preg[29:29] <= 1'b0;
    opad_buffer_10_preg[33:31] <= 3'b000;
    opad_buffer_10_preg[37:37] <= 1'b0;
    opad_buffer_10_preg[41:39] <= 3'b000;
    opad_buffer_10_preg[45:45] <= 1'b0;
    opad_buffer_10_preg[49:47] <= 3'b000;
    opad_buffer_10_preg[53:53] <= 1'b0;
    opad_buffer_10_preg[57:55] <= 3'b000;
    opad_buffer_10_preg[61] <= 1'b0;
    opad_buffer_11_preg[1:0] <= 2'b00;
    opad_buffer_11_preg[5:5] <= 1'b0;
    opad_buffer_11_preg[9:7] <= 3'b000;
    opad_buffer_11_preg[13:13] <= 1'b0;
    opad_buffer_11_preg[17:15] <= 3'b000;
    opad_buffer_11_preg[21:21] <= 1'b0;
    opad_buffer_11_preg[25:23] <= 3'b000;
    opad_buffer_11_preg[29:29] <= 1'b0;
    opad_buffer_11_preg[33:31] <= 3'b000;
    opad_buffer_11_preg[37:37] <= 1'b0;
    opad_buffer_11_preg[41:39] <= 3'b000;
    opad_buffer_11_preg[45:45] <= 1'b0;
    opad_buffer_11_preg[49:47] <= 3'b000;
    opad_buffer_11_preg[53:53] <= 1'b0;
    opad_buffer_11_preg[57:55] <= 3'b000;
    opad_buffer_11_preg[61] <= 1'b0;
    opad_buffer_12_preg[1:0] <= 2'b00;
    opad_buffer_12_preg[5:5] <= 1'b0;
    opad_buffer_12_preg[9:7] <= 3'b000;
    opad_buffer_12_preg[13:13] <= 1'b0;
    opad_buffer_12_preg[17:15] <= 3'b000;
    opad_buffer_12_preg[21:21] <= 1'b0;
    opad_buffer_12_preg[25:23] <= 3'b000;
    opad_buffer_12_preg[29:29] <= 1'b0;
    opad_buffer_12_preg[33:31] <= 3'b000;
    opad_buffer_12_preg[37:37] <= 1'b0;
    opad_buffer_12_preg[41:39] <= 3'b000;
    opad_buffer_12_preg[45:45] <= 1'b0;
    opad_buffer_12_preg[49:47] <= 3'b000;
    opad_buffer_12_preg[53:53] <= 1'b0;
    opad_buffer_12_preg[57:55] <= 3'b000;
    opad_buffer_12_preg[61] <= 1'b0;
    opad_buffer_13_preg[1:0] <= 2'b00;
    opad_buffer_13_preg[5:5] <= 1'b0;
    opad_buffer_13_preg[9:7] <= 3'b000;
    opad_buffer_13_preg[13:13] <= 1'b0;
    opad_buffer_13_preg[17:15] <= 3'b000;
    opad_buffer_13_preg[21:21] <= 1'b0;
    opad_buffer_13_preg[25:23] <= 3'b000;
    opad_buffer_13_preg[29:29] <= 1'b0;
    opad_buffer_13_preg[33:31] <= 3'b000;
    opad_buffer_13_preg[37:37] <= 1'b0;
    opad_buffer_13_preg[41:39] <= 3'b000;
    opad_buffer_13_preg[45:45] <= 1'b0;
    opad_buffer_13_preg[49:47] <= 3'b000;
    opad_buffer_13_preg[53:53] <= 1'b0;
    opad_buffer_13_preg[57:55] <= 3'b000;
    opad_buffer_13_preg[61] <= 1'b0;
    opad_buffer_14_preg[1:0] <= 2'b00;
    opad_buffer_14_preg[5:5] <= 1'b0;
    opad_buffer_14_preg[9:7] <= 3'b000;
    opad_buffer_14_preg[13:13] <= 1'b0;
    opad_buffer_14_preg[17:15] <= 3'b000;
    opad_buffer_14_preg[21:21] <= 1'b0;
    opad_buffer_14_preg[25:23] <= 3'b000;
    opad_buffer_14_preg[29:29] <= 1'b0;
    opad_buffer_14_preg[33:31] <= 3'b000;
    opad_buffer_14_preg[37:37] <= 1'b0;
    opad_buffer_14_preg[41:39] <= 3'b000;
    opad_buffer_14_preg[45:45] <= 1'b0;
    opad_buffer_14_preg[49:47] <= 3'b000;
    opad_buffer_14_preg[53:53] <= 1'b0;
    opad_buffer_14_preg[57:55] <= 3'b000;
    opad_buffer_14_preg[61] <= 1'b0;
    opad_buffer_15_preg[1:0] <= 2'b00;
    opad_buffer_15_preg[5:5] <= 1'b0;
    opad_buffer_15_preg[9:7] <= 3'b000;
    opad_buffer_15_preg[13:13] <= 1'b0;
    opad_buffer_15_preg[17:15] <= 3'b000;
    opad_buffer_15_preg[21:21] <= 1'b0;
    opad_buffer_15_preg[25:23] <= 3'b000;
    opad_buffer_15_preg[29:29] <= 1'b0;
    opad_buffer_15_preg[33:31] <= 3'b000;
    opad_buffer_15_preg[37:37] <= 1'b0;
    opad_buffer_15_preg[41:39] <= 3'b000;
    opad_buffer_15_preg[45:45] <= 1'b0;
    opad_buffer_15_preg[49:47] <= 3'b000;
    opad_buffer_15_preg[53:53] <= 1'b0;
    opad_buffer_15_preg[57:55] <= 3'b000;
    opad_buffer_15_preg[61] <= 1'b0;
end

endmodule //hmac_verify_preProcessingOneTripForHMAC23
