// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_sha256_Pipeline_VITIS_LOOP_36_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv74_lcssa139,
        conv72_lcssa137,
        conv70_lcssa135,
        conv68_lcssa133,
        conv66_lcssa131,
        conv64_lcssa129,
        conv62_lcssa127,
        conv60_lcssa125,
        conv58_lcssa123,
        conv56_lcssa121,
        conv54_lcssa119,
        conv52_lcssa117,
        conv50_lcssa115,
        conv48_lcssa113,
        conv46_lcssa111,
        conv44_lcssa109,
        conv42_lcssa107,
        conv40_lcssa105,
        conv38_lcssa103,
        conv36_lcssa101,
        conv34_lcssa99,
        conv32_lcssa97,
        conv30_lcssa95,
        conv28_lcssa93,
        conv26_lcssa91,
        conv24_lcssa89,
        conv22_lcssa87,
        conv20_lcssa85,
        conv18_lcssa83,
        conv16_lcssa81,
        conv14_lcssa79,
        conv12_lcssa77,
        seg_buf_31,
        seg_buf_30,
        seg_buf_29,
        seg_buf_28,
        seg_buf_27,
        seg_buf_26,
        seg_buf_25,
        seg_buf_24,
        seg_buf_23,
        seg_buf_22,
        seg_buf_21,
        seg_buf_20,
        seg_buf_19,
        seg_buf_18,
        seg_buf_17,
        seg_buf_16,
        seg_buf_15,
        seg_buf_14,
        seg_buf_13,
        seg_buf_12,
        seg_buf_11,
        seg_buf_10,
        seg_buf_9,
        seg_buf_8,
        seg_buf_7,
        seg_buf_6,
        seg_buf_5,
        seg_buf_4,
        seg_buf_3,
        seg_buf_2,
        seg_buf_1,
        seg_buf,
        trunc_ln145_1,
        seg_buf_96_out,
        seg_buf_96_out_ap_vld,
        seg_buf_95_out,
        seg_buf_95_out_ap_vld,
        seg_buf_94_out,
        seg_buf_94_out_ap_vld,
        seg_buf_93_out,
        seg_buf_93_out_ap_vld,
        seg_buf_92_out,
        seg_buf_92_out_ap_vld,
        seg_buf_91_out,
        seg_buf_91_out_ap_vld,
        seg_buf_90_out,
        seg_buf_90_out_ap_vld,
        seg_buf_89_out,
        seg_buf_89_out_ap_vld,
        seg_buf_88_out,
        seg_buf_88_out_ap_vld,
        seg_buf_87_out,
        seg_buf_87_out_ap_vld,
        seg_buf_86_out,
        seg_buf_86_out_ap_vld,
        seg_buf_85_out,
        seg_buf_85_out_ap_vld,
        seg_buf_84_out,
        seg_buf_84_out_ap_vld,
        seg_buf_83_out,
        seg_buf_83_out_ap_vld,
        seg_buf_82_out,
        seg_buf_82_out_ap_vld,
        seg_buf_81_out,
        seg_buf_81_out_ap_vld,
        seg_buf_80_out,
        seg_buf_80_out_ap_vld,
        seg_buf_79_out,
        seg_buf_79_out_ap_vld,
        seg_buf_78_out,
        seg_buf_78_out_ap_vld,
        seg_buf_77_out,
        seg_buf_77_out_ap_vld,
        seg_buf_76_out,
        seg_buf_76_out_ap_vld,
        seg_buf_75_out,
        seg_buf_75_out_ap_vld,
        seg_buf_74_out,
        seg_buf_74_out_ap_vld,
        seg_buf_73_out,
        seg_buf_73_out_ap_vld,
        seg_buf_72_out,
        seg_buf_72_out_ap_vld,
        seg_buf_71_out,
        seg_buf_71_out_ap_vld,
        seg_buf_70_out,
        seg_buf_70_out_ap_vld,
        seg_buf_69_out,
        seg_buf_69_out_ap_vld,
        seg_buf_68_out,
        seg_buf_68_out_ap_vld,
        seg_buf_67_out,
        seg_buf_67_out_ap_vld,
        seg_buf_66_out,
        seg_buf_66_out_ap_vld,
        seg_buf_65_out,
        seg_buf_65_out_ap_vld,
        seg_buf_63_out,
        seg_buf_63_out_ap_vld,
        seg_buf_62_out,
        seg_buf_62_out_ap_vld,
        seg_buf_61_out,
        seg_buf_61_out_ap_vld,
        seg_buf_60_out,
        seg_buf_60_out_ap_vld,
        seg_buf_59_out,
        seg_buf_59_out_ap_vld,
        seg_buf_58_out,
        seg_buf_58_out_ap_vld,
        seg_buf_57_out,
        seg_buf_57_out_ap_vld,
        seg_buf_56_out,
        seg_buf_56_out_ap_vld,
        seg_buf_55_out,
        seg_buf_55_out_ap_vld,
        seg_buf_54_out,
        seg_buf_54_out_ap_vld,
        seg_buf_53_out,
        seg_buf_53_out_ap_vld,
        seg_buf_52_out,
        seg_buf_52_out_ap_vld,
        seg_buf_51_out,
        seg_buf_51_out_ap_vld,
        seg_buf_50_out,
        seg_buf_50_out_ap_vld,
        seg_buf_49_out,
        seg_buf_49_out_ap_vld,
        seg_buf_48_out,
        seg_buf_48_out_ap_vld,
        seg_buf_47_out,
        seg_buf_47_out_ap_vld,
        seg_buf_46_out,
        seg_buf_46_out_ap_vld,
        seg_buf_45_out,
        seg_buf_45_out_ap_vld,
        seg_buf_44_out,
        seg_buf_44_out_ap_vld,
        seg_buf_43_out,
        seg_buf_43_out_ap_vld,
        seg_buf_42_out,
        seg_buf_42_out_ap_vld,
        seg_buf_41_out,
        seg_buf_41_out_ap_vld,
        seg_buf_40_out,
        seg_buf_40_out_ap_vld,
        seg_buf_39_out,
        seg_buf_39_out_ap_vld,
        seg_buf_38_out,
        seg_buf_38_out_ap_vld,
        seg_buf_37_out,
        seg_buf_37_out_ap_vld,
        seg_buf_36_out,
        seg_buf_36_out_ap_vld,
        seg_buf_35_out,
        seg_buf_35_out_ap_vld,
        seg_buf_34_out,
        seg_buf_34_out_ap_vld,
        seg_buf_33_out,
        seg_buf_33_out_ap_vld,
        seg_buf_32_out,
        seg_buf_32_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] conv74_lcssa139;
input  [7:0] conv72_lcssa137;
input  [7:0] conv70_lcssa135;
input  [7:0] conv68_lcssa133;
input  [7:0] conv66_lcssa131;
input  [7:0] conv64_lcssa129;
input  [7:0] conv62_lcssa127;
input  [7:0] conv60_lcssa125;
input  [7:0] conv58_lcssa123;
input  [7:0] conv56_lcssa121;
input  [7:0] conv54_lcssa119;
input  [7:0] conv52_lcssa117;
input  [7:0] conv50_lcssa115;
input  [7:0] conv48_lcssa113;
input  [7:0] conv46_lcssa111;
input  [7:0] conv44_lcssa109;
input  [7:0] conv42_lcssa107;
input  [7:0] conv40_lcssa105;
input  [7:0] conv38_lcssa103;
input  [7:0] conv36_lcssa101;
input  [7:0] conv34_lcssa99;
input  [7:0] conv32_lcssa97;
input  [7:0] conv30_lcssa95;
input  [7:0] conv28_lcssa93;
input  [7:0] conv26_lcssa91;
input  [7:0] conv24_lcssa89;
input  [7:0] conv22_lcssa87;
input  [7:0] conv20_lcssa85;
input  [7:0] conv18_lcssa83;
input  [7:0] conv16_lcssa81;
input  [7:0] conv14_lcssa79;
input  [7:0] conv12_lcssa77;
input  [7:0] seg_buf_31;
input  [7:0] seg_buf_30;
input  [7:0] seg_buf_29;
input  [7:0] seg_buf_28;
input  [7:0] seg_buf_27;
input  [7:0] seg_buf_26;
input  [7:0] seg_buf_25;
input  [7:0] seg_buf_24;
input  [7:0] seg_buf_23;
input  [7:0] seg_buf_22;
input  [7:0] seg_buf_21;
input  [7:0] seg_buf_20;
input  [7:0] seg_buf_19;
input  [7:0] seg_buf_18;
input  [7:0] seg_buf_17;
input  [7:0] seg_buf_16;
input  [7:0] seg_buf_15;
input  [7:0] seg_buf_14;
input  [7:0] seg_buf_13;
input  [7:0] seg_buf_12;
input  [7:0] seg_buf_11;
input  [7:0] seg_buf_10;
input  [7:0] seg_buf_9;
input  [7:0] seg_buf_8;
input  [7:0] seg_buf_7;
input  [7:0] seg_buf_6;
input  [7:0] seg_buf_5;
input  [7:0] seg_buf_4;
input  [7:0] seg_buf_3;
input  [7:0] seg_buf_2;
input  [7:0] seg_buf_1;
input  [7:0] seg_buf;
input  [511:0] trunc_ln145_1;
output  [7:0] seg_buf_96_out;
output   seg_buf_96_out_ap_vld;
output  [7:0] seg_buf_95_out;
output   seg_buf_95_out_ap_vld;
output  [7:0] seg_buf_94_out;
output   seg_buf_94_out_ap_vld;
output  [7:0] seg_buf_93_out;
output   seg_buf_93_out_ap_vld;
output  [7:0] seg_buf_92_out;
output   seg_buf_92_out_ap_vld;
output  [7:0] seg_buf_91_out;
output   seg_buf_91_out_ap_vld;
output  [7:0] seg_buf_90_out;
output   seg_buf_90_out_ap_vld;
output  [7:0] seg_buf_89_out;
output   seg_buf_89_out_ap_vld;
output  [7:0] seg_buf_88_out;
output   seg_buf_88_out_ap_vld;
output  [7:0] seg_buf_87_out;
output   seg_buf_87_out_ap_vld;
output  [7:0] seg_buf_86_out;
output   seg_buf_86_out_ap_vld;
output  [7:0] seg_buf_85_out;
output   seg_buf_85_out_ap_vld;
output  [7:0] seg_buf_84_out;
output   seg_buf_84_out_ap_vld;
output  [7:0] seg_buf_83_out;
output   seg_buf_83_out_ap_vld;
output  [7:0] seg_buf_82_out;
output   seg_buf_82_out_ap_vld;
output  [7:0] seg_buf_81_out;
output   seg_buf_81_out_ap_vld;
output  [7:0] seg_buf_80_out;
output   seg_buf_80_out_ap_vld;
output  [7:0] seg_buf_79_out;
output   seg_buf_79_out_ap_vld;
output  [7:0] seg_buf_78_out;
output   seg_buf_78_out_ap_vld;
output  [7:0] seg_buf_77_out;
output   seg_buf_77_out_ap_vld;
output  [7:0] seg_buf_76_out;
output   seg_buf_76_out_ap_vld;
output  [7:0] seg_buf_75_out;
output   seg_buf_75_out_ap_vld;
output  [7:0] seg_buf_74_out;
output   seg_buf_74_out_ap_vld;
output  [7:0] seg_buf_73_out;
output   seg_buf_73_out_ap_vld;
output  [7:0] seg_buf_72_out;
output   seg_buf_72_out_ap_vld;
output  [7:0] seg_buf_71_out;
output   seg_buf_71_out_ap_vld;
output  [7:0] seg_buf_70_out;
output   seg_buf_70_out_ap_vld;
output  [7:0] seg_buf_69_out;
output   seg_buf_69_out_ap_vld;
output  [7:0] seg_buf_68_out;
output   seg_buf_68_out_ap_vld;
output  [7:0] seg_buf_67_out;
output   seg_buf_67_out_ap_vld;
output  [7:0] seg_buf_66_out;
output   seg_buf_66_out_ap_vld;
output  [7:0] seg_buf_65_out;
output   seg_buf_65_out_ap_vld;
output  [7:0] seg_buf_63_out;
output   seg_buf_63_out_ap_vld;
output  [7:0] seg_buf_62_out;
output   seg_buf_62_out_ap_vld;
output  [7:0] seg_buf_61_out;
output   seg_buf_61_out_ap_vld;
output  [7:0] seg_buf_60_out;
output   seg_buf_60_out_ap_vld;
output  [7:0] seg_buf_59_out;
output   seg_buf_59_out_ap_vld;
output  [7:0] seg_buf_58_out;
output   seg_buf_58_out_ap_vld;
output  [7:0] seg_buf_57_out;
output   seg_buf_57_out_ap_vld;
output  [7:0] seg_buf_56_out;
output   seg_buf_56_out_ap_vld;
output  [7:0] seg_buf_55_out;
output   seg_buf_55_out_ap_vld;
output  [7:0] seg_buf_54_out;
output   seg_buf_54_out_ap_vld;
output  [7:0] seg_buf_53_out;
output   seg_buf_53_out_ap_vld;
output  [7:0] seg_buf_52_out;
output   seg_buf_52_out_ap_vld;
output  [7:0] seg_buf_51_out;
output   seg_buf_51_out_ap_vld;
output  [7:0] seg_buf_50_out;
output   seg_buf_50_out_ap_vld;
output  [7:0] seg_buf_49_out;
output   seg_buf_49_out_ap_vld;
output  [7:0] seg_buf_48_out;
output   seg_buf_48_out_ap_vld;
output  [7:0] seg_buf_47_out;
output   seg_buf_47_out_ap_vld;
output  [7:0] seg_buf_46_out;
output   seg_buf_46_out_ap_vld;
output  [7:0] seg_buf_45_out;
output   seg_buf_45_out_ap_vld;
output  [7:0] seg_buf_44_out;
output   seg_buf_44_out_ap_vld;
output  [7:0] seg_buf_43_out;
output   seg_buf_43_out_ap_vld;
output  [7:0] seg_buf_42_out;
output   seg_buf_42_out_ap_vld;
output  [7:0] seg_buf_41_out;
output   seg_buf_41_out_ap_vld;
output  [7:0] seg_buf_40_out;
output   seg_buf_40_out_ap_vld;
output  [7:0] seg_buf_39_out;
output   seg_buf_39_out_ap_vld;
output  [7:0] seg_buf_38_out;
output   seg_buf_38_out_ap_vld;
output  [7:0] seg_buf_37_out;
output   seg_buf_37_out_ap_vld;
output  [7:0] seg_buf_36_out;
output   seg_buf_36_out_ap_vld;
output  [7:0] seg_buf_35_out;
output   seg_buf_35_out_ap_vld;
output  [7:0] seg_buf_34_out;
output   seg_buf_34_out_ap_vld;
output  [7:0] seg_buf_33_out;
output   seg_buf_33_out_ap_vld;
output  [7:0] seg_buf_32_out;
output   seg_buf_32_out_ap_vld;

reg ap_idle;
reg seg_buf_96_out_ap_vld;
reg seg_buf_95_out_ap_vld;
reg seg_buf_94_out_ap_vld;
reg seg_buf_93_out_ap_vld;
reg seg_buf_92_out_ap_vld;
reg seg_buf_91_out_ap_vld;
reg seg_buf_90_out_ap_vld;
reg seg_buf_89_out_ap_vld;
reg seg_buf_88_out_ap_vld;
reg seg_buf_87_out_ap_vld;
reg seg_buf_86_out_ap_vld;
reg seg_buf_85_out_ap_vld;
reg seg_buf_84_out_ap_vld;
reg seg_buf_83_out_ap_vld;
reg seg_buf_82_out_ap_vld;
reg seg_buf_81_out_ap_vld;
reg seg_buf_80_out_ap_vld;
reg seg_buf_79_out_ap_vld;
reg seg_buf_78_out_ap_vld;
reg seg_buf_77_out_ap_vld;
reg seg_buf_76_out_ap_vld;
reg seg_buf_75_out_ap_vld;
reg seg_buf_74_out_ap_vld;
reg seg_buf_73_out_ap_vld;
reg seg_buf_72_out_ap_vld;
reg seg_buf_71_out_ap_vld;
reg seg_buf_70_out_ap_vld;
reg seg_buf_69_out_ap_vld;
reg seg_buf_68_out_ap_vld;
reg seg_buf_67_out_ap_vld;
reg seg_buf_66_out_ap_vld;
reg seg_buf_65_out_ap_vld;
reg seg_buf_63_out_ap_vld;
reg seg_buf_62_out_ap_vld;
reg seg_buf_61_out_ap_vld;
reg seg_buf_60_out_ap_vld;
reg seg_buf_59_out_ap_vld;
reg seg_buf_58_out_ap_vld;
reg seg_buf_57_out_ap_vld;
reg seg_buf_56_out_ap_vld;
reg seg_buf_55_out_ap_vld;
reg seg_buf_54_out_ap_vld;
reg seg_buf_53_out_ap_vld;
reg seg_buf_52_out_ap_vld;
reg seg_buf_51_out_ap_vld;
reg seg_buf_50_out_ap_vld;
reg seg_buf_49_out_ap_vld;
reg seg_buf_48_out_ap_vld;
reg seg_buf_47_out_ap_vld;
reg seg_buf_46_out_ap_vld;
reg seg_buf_45_out_ap_vld;
reg seg_buf_44_out_ap_vld;
reg seg_buf_43_out_ap_vld;
reg seg_buf_42_out_ap_vld;
reg seg_buf_41_out_ap_vld;
reg seg_buf_40_out_ap_vld;
reg seg_buf_39_out_ap_vld;
reg seg_buf_38_out_ap_vld;
reg seg_buf_37_out_ap_vld;
reg seg_buf_36_out_ap_vld;
reg seg_buf_35_out_ap_vld;
reg seg_buf_34_out_ap_vld;
reg seg_buf_33_out_ap_vld;
reg seg_buf_32_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln36_fu_1846_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] i_fu_420;
wire   [6:0] add_ln36_fu_1852_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_7;
reg   [7:0] seg_buf_32_fu_424;
wire   [7:0] seg_buf_96_fu_1880_p1;
wire   [5:0] xor_ln37_fu_1884_p2;
reg   [7:0] seg_buf_33_fu_428;
reg   [7:0] seg_buf_34_fu_432;
reg   [7:0] seg_buf_35_fu_436;
reg   [7:0] seg_buf_36_fu_440;
reg   [7:0] seg_buf_37_fu_444;
reg   [7:0] seg_buf_38_fu_448;
reg   [7:0] seg_buf_39_fu_452;
reg   [7:0] seg_buf_40_fu_456;
reg   [7:0] seg_buf_41_fu_460;
reg   [7:0] seg_buf_42_fu_464;
reg   [7:0] seg_buf_43_fu_468;
reg   [7:0] seg_buf_44_fu_472;
reg   [7:0] seg_buf_45_fu_476;
reg   [7:0] seg_buf_46_fu_480;
reg   [7:0] seg_buf_47_fu_484;
reg   [7:0] seg_buf_48_fu_488;
reg   [7:0] seg_buf_49_fu_492;
reg   [7:0] seg_buf_50_fu_496;
reg   [7:0] seg_buf_51_fu_500;
reg   [7:0] seg_buf_52_fu_504;
reg   [7:0] seg_buf_53_fu_508;
reg   [7:0] seg_buf_54_fu_512;
reg   [7:0] seg_buf_55_fu_516;
reg   [7:0] seg_buf_56_fu_520;
reg   [7:0] seg_buf_57_fu_524;
reg   [7:0] seg_buf_58_fu_528;
reg   [7:0] seg_buf_59_fu_532;
reg   [7:0] seg_buf_60_fu_536;
reg   [7:0] seg_buf_61_fu_540;
reg   [7:0] seg_buf_62_fu_544;
reg   [7:0] seg_buf_63_fu_548;
reg   [7:0] seg_buf_64_fu_552;
reg   [7:0] seg_buf_65_fu_556;
reg   [7:0] seg_buf_66_fu_560;
reg   [7:0] seg_buf_67_fu_564;
reg   [7:0] seg_buf_68_fu_568;
reg   [7:0] seg_buf_69_fu_572;
reg   [7:0] seg_buf_70_fu_576;
reg   [7:0] seg_buf_71_fu_580;
reg   [7:0] seg_buf_72_fu_584;
reg   [7:0] seg_buf_73_fu_588;
reg   [7:0] seg_buf_74_fu_592;
reg   [7:0] seg_buf_75_fu_596;
reg   [7:0] seg_buf_76_fu_600;
reg   [7:0] seg_buf_77_fu_604;
reg   [7:0] seg_buf_78_fu_608;
reg   [7:0] seg_buf_79_fu_612;
reg   [7:0] seg_buf_80_fu_616;
reg   [7:0] seg_buf_81_fu_620;
reg   [7:0] seg_buf_82_fu_624;
reg   [7:0] seg_buf_83_fu_628;
reg   [7:0] seg_buf_84_fu_632;
reg   [7:0] seg_buf_85_fu_636;
reg   [7:0] seg_buf_86_fu_640;
reg   [7:0] seg_buf_87_fu_644;
reg   [7:0] seg_buf_88_fu_648;
reg   [7:0] seg_buf_89_fu_652;
reg   [7:0] seg_buf_90_fu_656;
reg   [7:0] seg_buf_91_fu_660;
reg   [7:0] seg_buf_92_fu_664;
reg   [7:0] seg_buf_93_fu_668;
reg   [7:0] seg_buf_94_fu_672;
reg   [7:0] seg_buf_95_fu_676;
wire   [5:0] trunc_ln37_fu_1858_p1;
wire   [8:0] shl_ln_fu_1862_p3;
wire   [511:0] zext_ln1715_fu_1870_p1;
wire   [511:0] r_V_fu_1874_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

sha256_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln36_fu_1846_p2 == 1'd0)) begin
            i_fu_420 <= add_ln36_fu_1852_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_420 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd32))) begin
            seg_buf_32_fu_424 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_32_fu_424 <= seg_buf;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd33))) begin
            seg_buf_33_fu_428 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_33_fu_428 <= seg_buf_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd34))) begin
            seg_buf_34_fu_432 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_34_fu_432 <= seg_buf_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd35))) begin
            seg_buf_35_fu_436 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_35_fu_436 <= seg_buf_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd36))) begin
            seg_buf_36_fu_440 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_36_fu_440 <= seg_buf_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd37))) begin
            seg_buf_37_fu_444 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_37_fu_444 <= seg_buf_5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd38))) begin
            seg_buf_38_fu_448 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_38_fu_448 <= seg_buf_6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd39))) begin
            seg_buf_39_fu_452 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_39_fu_452 <= seg_buf_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd40))) begin
            seg_buf_40_fu_456 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_40_fu_456 <= seg_buf_8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd41))) begin
            seg_buf_41_fu_460 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_41_fu_460 <= seg_buf_9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd42))) begin
            seg_buf_42_fu_464 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_42_fu_464 <= seg_buf_10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd43))) begin
            seg_buf_43_fu_468 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_43_fu_468 <= seg_buf_11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd44))) begin
            seg_buf_44_fu_472 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_44_fu_472 <= seg_buf_12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd45))) begin
            seg_buf_45_fu_476 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_45_fu_476 <= seg_buf_13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd46))) begin
            seg_buf_46_fu_480 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_46_fu_480 <= seg_buf_14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd47))) begin
            seg_buf_47_fu_484 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_47_fu_484 <= seg_buf_15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd48))) begin
            seg_buf_48_fu_488 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_48_fu_488 <= seg_buf_16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd49))) begin
            seg_buf_49_fu_492 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_49_fu_492 <= seg_buf_17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd50))) begin
            seg_buf_50_fu_496 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_50_fu_496 <= seg_buf_18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd51))) begin
            seg_buf_51_fu_500 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_51_fu_500 <= seg_buf_19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd52))) begin
            seg_buf_52_fu_504 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_52_fu_504 <= seg_buf_20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd53))) begin
            seg_buf_53_fu_508 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_53_fu_508 <= seg_buf_21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd54))) begin
            seg_buf_54_fu_512 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_54_fu_512 <= seg_buf_22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd55))) begin
            seg_buf_55_fu_516 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_55_fu_516 <= seg_buf_23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd56))) begin
            seg_buf_56_fu_520 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_56_fu_520 <= seg_buf_24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd57))) begin
            seg_buf_57_fu_524 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_57_fu_524 <= seg_buf_25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd58))) begin
            seg_buf_58_fu_528 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_58_fu_528 <= seg_buf_26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd59))) begin
            seg_buf_59_fu_532 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_59_fu_532 <= seg_buf_27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd60))) begin
            seg_buf_60_fu_536 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_60_fu_536 <= seg_buf_28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd61))) begin
            seg_buf_61_fu_540 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_61_fu_540 <= seg_buf_29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd62))) begin
            seg_buf_62_fu_544 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_62_fu_544 <= seg_buf_30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd63))) begin
            seg_buf_63_fu_548 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_63_fu_548 <= seg_buf_31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd31))) begin
            seg_buf_64_fu_552 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_64_fu_552 <= conv12_lcssa77;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd30))) begin
            seg_buf_65_fu_556 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_65_fu_556 <= conv14_lcssa79;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd29))) begin
            seg_buf_66_fu_560 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_66_fu_560 <= conv16_lcssa81;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd28))) begin
            seg_buf_67_fu_564 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_67_fu_564 <= conv18_lcssa83;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd27))) begin
            seg_buf_68_fu_568 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_68_fu_568 <= conv20_lcssa85;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd26))) begin
            seg_buf_69_fu_572 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_69_fu_572 <= conv22_lcssa87;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd25))) begin
            seg_buf_70_fu_576 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_70_fu_576 <= conv24_lcssa89;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd24))) begin
            seg_buf_71_fu_580 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_71_fu_580 <= conv26_lcssa91;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd23))) begin
            seg_buf_72_fu_584 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_72_fu_584 <= conv28_lcssa93;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd22))) begin
            seg_buf_73_fu_588 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_73_fu_588 <= conv30_lcssa95;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd21))) begin
            seg_buf_74_fu_592 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_74_fu_592 <= conv32_lcssa97;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd20))) begin
            seg_buf_75_fu_596 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_75_fu_596 <= conv34_lcssa99;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd19))) begin
            seg_buf_76_fu_600 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_76_fu_600 <= conv36_lcssa101;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd18))) begin
            seg_buf_77_fu_604 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_77_fu_604 <= conv38_lcssa103;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd17))) begin
            seg_buf_78_fu_608 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_78_fu_608 <= conv40_lcssa105;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd16))) begin
            seg_buf_79_fu_612 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_79_fu_612 <= conv42_lcssa107;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd15))) begin
            seg_buf_80_fu_616 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_80_fu_616 <= conv44_lcssa109;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd14))) begin
            seg_buf_81_fu_620 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_81_fu_620 <= conv46_lcssa111;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd13))) begin
            seg_buf_82_fu_624 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_82_fu_624 <= conv48_lcssa113;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd12))) begin
            seg_buf_83_fu_628 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_83_fu_628 <= conv50_lcssa115;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd11))) begin
            seg_buf_84_fu_632 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_84_fu_632 <= conv52_lcssa117;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd10))) begin
            seg_buf_85_fu_636 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_85_fu_636 <= conv54_lcssa119;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd9))) begin
            seg_buf_86_fu_640 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_86_fu_640 <= conv56_lcssa121;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd8))) begin
            seg_buf_87_fu_644 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_87_fu_644 <= conv58_lcssa123;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd7))) begin
            seg_buf_88_fu_648 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_88_fu_648 <= conv60_lcssa125;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd6))) begin
            seg_buf_89_fu_652 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_89_fu_652 <= conv62_lcssa127;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd5))) begin
            seg_buf_90_fu_656 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_90_fu_656 <= conv64_lcssa129;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd4))) begin
            seg_buf_91_fu_660 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_91_fu_660 <= conv66_lcssa131;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd3))) begin
            seg_buf_92_fu_664 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_92_fu_664 <= conv68_lcssa133;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd2))) begin
            seg_buf_93_fu_668 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_93_fu_668 <= conv70_lcssa135;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd1))) begin
            seg_buf_94_fu_672 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_94_fu_672 <= conv72_lcssa137;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln36_fu_1846_p2 == 1'd0) & (xor_ln37_fu_1884_p2 == 6'd0))) begin
            seg_buf_95_fu_676 <= seg_buf_96_fu_1880_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            seg_buf_95_fu_676 <= conv74_lcssa139;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_7 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_7 = i_fu_420;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_32_out_ap_vld = 1'b1;
    end else begin
        seg_buf_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_33_out_ap_vld = 1'b1;
    end else begin
        seg_buf_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_34_out_ap_vld = 1'b1;
    end else begin
        seg_buf_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_35_out_ap_vld = 1'b1;
    end else begin
        seg_buf_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_36_out_ap_vld = 1'b1;
    end else begin
        seg_buf_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_37_out_ap_vld = 1'b1;
    end else begin
        seg_buf_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_38_out_ap_vld = 1'b1;
    end else begin
        seg_buf_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_39_out_ap_vld = 1'b1;
    end else begin
        seg_buf_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_40_out_ap_vld = 1'b1;
    end else begin
        seg_buf_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_41_out_ap_vld = 1'b1;
    end else begin
        seg_buf_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_42_out_ap_vld = 1'b1;
    end else begin
        seg_buf_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_43_out_ap_vld = 1'b1;
    end else begin
        seg_buf_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_44_out_ap_vld = 1'b1;
    end else begin
        seg_buf_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_45_out_ap_vld = 1'b1;
    end else begin
        seg_buf_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_46_out_ap_vld = 1'b1;
    end else begin
        seg_buf_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_47_out_ap_vld = 1'b1;
    end else begin
        seg_buf_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_48_out_ap_vld = 1'b1;
    end else begin
        seg_buf_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_49_out_ap_vld = 1'b1;
    end else begin
        seg_buf_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_50_out_ap_vld = 1'b1;
    end else begin
        seg_buf_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_51_out_ap_vld = 1'b1;
    end else begin
        seg_buf_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_52_out_ap_vld = 1'b1;
    end else begin
        seg_buf_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_53_out_ap_vld = 1'b1;
    end else begin
        seg_buf_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_54_out_ap_vld = 1'b1;
    end else begin
        seg_buf_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_55_out_ap_vld = 1'b1;
    end else begin
        seg_buf_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_56_out_ap_vld = 1'b1;
    end else begin
        seg_buf_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_57_out_ap_vld = 1'b1;
    end else begin
        seg_buf_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_58_out_ap_vld = 1'b1;
    end else begin
        seg_buf_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_59_out_ap_vld = 1'b1;
    end else begin
        seg_buf_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_60_out_ap_vld = 1'b1;
    end else begin
        seg_buf_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_61_out_ap_vld = 1'b1;
    end else begin
        seg_buf_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_62_out_ap_vld = 1'b1;
    end else begin
        seg_buf_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_63_out_ap_vld = 1'b1;
    end else begin
        seg_buf_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_65_out_ap_vld = 1'b1;
    end else begin
        seg_buf_65_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_66_out_ap_vld = 1'b1;
    end else begin
        seg_buf_66_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_67_out_ap_vld = 1'b1;
    end else begin
        seg_buf_67_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_68_out_ap_vld = 1'b1;
    end else begin
        seg_buf_68_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_69_out_ap_vld = 1'b1;
    end else begin
        seg_buf_69_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_70_out_ap_vld = 1'b1;
    end else begin
        seg_buf_70_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_71_out_ap_vld = 1'b1;
    end else begin
        seg_buf_71_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_72_out_ap_vld = 1'b1;
    end else begin
        seg_buf_72_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_73_out_ap_vld = 1'b1;
    end else begin
        seg_buf_73_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_74_out_ap_vld = 1'b1;
    end else begin
        seg_buf_74_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_75_out_ap_vld = 1'b1;
    end else begin
        seg_buf_75_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_76_out_ap_vld = 1'b1;
    end else begin
        seg_buf_76_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_77_out_ap_vld = 1'b1;
    end else begin
        seg_buf_77_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_78_out_ap_vld = 1'b1;
    end else begin
        seg_buf_78_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_79_out_ap_vld = 1'b1;
    end else begin
        seg_buf_79_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_80_out_ap_vld = 1'b1;
    end else begin
        seg_buf_80_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_81_out_ap_vld = 1'b1;
    end else begin
        seg_buf_81_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_82_out_ap_vld = 1'b1;
    end else begin
        seg_buf_82_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_83_out_ap_vld = 1'b1;
    end else begin
        seg_buf_83_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_84_out_ap_vld = 1'b1;
    end else begin
        seg_buf_84_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_85_out_ap_vld = 1'b1;
    end else begin
        seg_buf_85_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_86_out_ap_vld = 1'b1;
    end else begin
        seg_buf_86_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_87_out_ap_vld = 1'b1;
    end else begin
        seg_buf_87_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_88_out_ap_vld = 1'b1;
    end else begin
        seg_buf_88_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_89_out_ap_vld = 1'b1;
    end else begin
        seg_buf_89_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_90_out_ap_vld = 1'b1;
    end else begin
        seg_buf_90_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_91_out_ap_vld = 1'b1;
    end else begin
        seg_buf_91_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_92_out_ap_vld = 1'b1;
    end else begin
        seg_buf_92_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_93_out_ap_vld = 1'b1;
    end else begin
        seg_buf_93_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_94_out_ap_vld = 1'b1;
    end else begin
        seg_buf_94_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_95_out_ap_vld = 1'b1;
    end else begin
        seg_buf_95_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_1846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_buf_96_out_ap_vld = 1'b1;
    end else begin
        seg_buf_96_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_fu_1852_p2 = (ap_sig_allocacmp_i_7 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln36_fu_1846_p2 = ((ap_sig_allocacmp_i_7 == 7'd64) ? 1'b1 : 1'b0);

assign r_V_fu_1874_p2 = trunc_ln145_1 >> zext_ln1715_fu_1870_p1;

assign seg_buf_32_out = seg_buf_32_fu_424;

assign seg_buf_33_out = seg_buf_33_fu_428;

assign seg_buf_34_out = seg_buf_34_fu_432;

assign seg_buf_35_out = seg_buf_35_fu_436;

assign seg_buf_36_out = seg_buf_36_fu_440;

assign seg_buf_37_out = seg_buf_37_fu_444;

assign seg_buf_38_out = seg_buf_38_fu_448;

assign seg_buf_39_out = seg_buf_39_fu_452;

assign seg_buf_40_out = seg_buf_40_fu_456;

assign seg_buf_41_out = seg_buf_41_fu_460;

assign seg_buf_42_out = seg_buf_42_fu_464;

assign seg_buf_43_out = seg_buf_43_fu_468;

assign seg_buf_44_out = seg_buf_44_fu_472;

assign seg_buf_45_out = seg_buf_45_fu_476;

assign seg_buf_46_out = seg_buf_46_fu_480;

assign seg_buf_47_out = seg_buf_47_fu_484;

assign seg_buf_48_out = seg_buf_48_fu_488;

assign seg_buf_49_out = seg_buf_49_fu_492;

assign seg_buf_50_out = seg_buf_50_fu_496;

assign seg_buf_51_out = seg_buf_51_fu_500;

assign seg_buf_52_out = seg_buf_52_fu_504;

assign seg_buf_53_out = seg_buf_53_fu_508;

assign seg_buf_54_out = seg_buf_54_fu_512;

assign seg_buf_55_out = seg_buf_55_fu_516;

assign seg_buf_56_out = seg_buf_56_fu_520;

assign seg_buf_57_out = seg_buf_57_fu_524;

assign seg_buf_58_out = seg_buf_58_fu_528;

assign seg_buf_59_out = seg_buf_59_fu_532;

assign seg_buf_60_out = seg_buf_60_fu_536;

assign seg_buf_61_out = seg_buf_61_fu_540;

assign seg_buf_62_out = seg_buf_62_fu_544;

assign seg_buf_63_out = seg_buf_63_fu_548;

assign seg_buf_65_out = seg_buf_64_fu_552;

assign seg_buf_66_out = seg_buf_65_fu_556;

assign seg_buf_67_out = seg_buf_66_fu_560;

assign seg_buf_68_out = seg_buf_67_fu_564;

assign seg_buf_69_out = seg_buf_68_fu_568;

assign seg_buf_70_out = seg_buf_69_fu_572;

assign seg_buf_71_out = seg_buf_70_fu_576;

assign seg_buf_72_out = seg_buf_71_fu_580;

assign seg_buf_73_out = seg_buf_72_fu_584;

assign seg_buf_74_out = seg_buf_73_fu_588;

assign seg_buf_75_out = seg_buf_74_fu_592;

assign seg_buf_76_out = seg_buf_75_fu_596;

assign seg_buf_77_out = seg_buf_76_fu_600;

assign seg_buf_78_out = seg_buf_77_fu_604;

assign seg_buf_79_out = seg_buf_78_fu_608;

assign seg_buf_80_out = seg_buf_79_fu_612;

assign seg_buf_81_out = seg_buf_80_fu_616;

assign seg_buf_82_out = seg_buf_81_fu_620;

assign seg_buf_83_out = seg_buf_82_fu_624;

assign seg_buf_84_out = seg_buf_83_fu_628;

assign seg_buf_85_out = seg_buf_84_fu_632;

assign seg_buf_86_out = seg_buf_85_fu_636;

assign seg_buf_87_out = seg_buf_86_fu_640;

assign seg_buf_88_out = seg_buf_87_fu_644;

assign seg_buf_89_out = seg_buf_88_fu_648;

assign seg_buf_90_out = seg_buf_89_fu_652;

assign seg_buf_91_out = seg_buf_90_fu_656;

assign seg_buf_92_out = seg_buf_91_fu_660;

assign seg_buf_93_out = seg_buf_92_fu_664;

assign seg_buf_94_out = seg_buf_93_fu_668;

assign seg_buf_95_out = seg_buf_94_fu_672;

assign seg_buf_96_fu_1880_p1 = r_V_fu_1874_p2[7:0];

assign seg_buf_96_out = seg_buf_95_fu_676;

assign shl_ln_fu_1862_p3 = {{trunc_ln37_fu_1858_p1}, {3'd0}};

assign trunc_ln37_fu_1858_p1 = ap_sig_allocacmp_i_7[5:0];

assign xor_ln37_fu_1884_p2 = (trunc_ln37_fu_1858_p1 ^ 6'd63);

assign zext_ln1715_fu_1870_p1 = shl_ln_fu_1862_p3;

endmodule //sha256_sha256_Pipeline_VITIS_LOOP_36_2
