// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hmac_HMAC_SHA384 (
        input_r_TDATA,
        output_r_TDATA,
        ap_clk,
        ap_rst,
        input_r_TVALID,
        input_r_TREADY,
        ap_start,
        output_r_TVALID,
        output_r_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [583:0] input_r_TDATA;
output  [583:0] output_r_TDATA;
input   ap_clk;
input   ap_rst;
input   input_r_TVALID;
output   input_r_TREADY;
input   ap_start;
output   output_r_TVALID;
input   output_r_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    injectData18_U0_ap_start;
wire    injectData18_U0_ap_done;
wire    injectData18_U0_ap_continue;
wire    injectData18_U0_ap_idle;
wire    injectData18_U0_ap_ready;
wire    injectData18_U0_start_out;
wire    injectData18_U0_start_write;
wire    injectData18_U0_input_r_TREADY;
wire   [511:0] injectData18_U0_msg_key_strm167_din;
wire    injectData18_U0_msg_key_strm167_write;
wire   [39:0] injectData18_U0_len_strm168_din;
wire    injectData18_U0_len_strm168_write;
wire   [63:0] injectData18_U0_ap_return_0;
wire   [5:0] injectData18_U0_ap_return_1;
wire    ap_channel_done_id_V;
wire    id_V_full_n;
reg    ap_sync_reg_channel_write_id_V;
wire    ap_sync_channel_write_id_V;
wire    ap_channel_done_keep_V;
wire    keep_V_full_n;
reg    ap_sync_reg_channel_write_keep_V;
wire    ap_sync_channel_write_keep_V;
wire   [63:0] HMAC_SHA384_2in119_U0_opad_buffer_0;
wire   [63:0] HMAC_SHA384_2in119_U0_opad_buffer_1;
wire   [63:0] HMAC_SHA384_2in119_U0_opad_buffer_2;
wire   [63:0] HMAC_SHA384_2in119_U0_opad_buffer_3;
wire   [63:0] HMAC_SHA384_2in119_U0_opad_buffer_4;
wire   [63:0] HMAC_SHA384_2in119_U0_opad_buffer_5;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_6;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_7;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_8;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_9;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_10;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_11;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_12;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_13;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_14;
wire   [62:0] HMAC_SHA384_2in119_U0_opad_buffer_15;
wire    HMAC_SHA384_2in119_U0_msg_key_strm167_read;
wire    HMAC_SHA384_2in119_U0_len_strm168_read;
wire   [383:0] HMAC_SHA384_2in119_U0_digest_output;
wire    HMAC_SHA384_2in119_U0_opad_buffer_0_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_1_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_2_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_3_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_4_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_5_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_6_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_7_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_8_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_9_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_10_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_11_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_12_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_13_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_14_ap_vld;
wire    HMAC_SHA384_2in119_U0_opad_buffer_15_ap_vld;
wire    HMAC_SHA384_2in119_U0_ap_start;
wire    HMAC_SHA384_2in119_U0_ap_done;
wire    HMAC_SHA384_2in119_U0_digest_output_ap_vld;
wire    HMAC_SHA384_2in119_U0_ap_ready;
wire    HMAC_SHA384_2in119_U0_ap_idle;
wire    HMAC_SHA384_2in119_U0_ap_continue;
wire    ap_channel_done_res_V_out_tmp_channel;
wire    res_V_out_tmp_channel_full_n;
reg    ap_sync_reg_channel_write_res_V_out_tmp_channel;
wire    ap_sync_channel_write_res_V_out_tmp_channel;
wire    ap_channel_done_opad_buffer_V_15;
wire    opad_buffer_V_15_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_15;
wire    ap_sync_channel_write_opad_buffer_V_15;
wire    ap_channel_done_opad_buffer_V_14;
wire    opad_buffer_V_14_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_14;
wire    ap_sync_channel_write_opad_buffer_V_14;
wire    ap_channel_done_opad_buffer_V_13;
wire    opad_buffer_V_13_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_13;
wire    ap_sync_channel_write_opad_buffer_V_13;
wire    ap_channel_done_opad_buffer_V_12;
wire    opad_buffer_V_12_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_12;
wire    ap_sync_channel_write_opad_buffer_V_12;
wire    ap_channel_done_opad_buffer_V_11;
wire    opad_buffer_V_11_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_11;
wire    ap_sync_channel_write_opad_buffer_V_11;
wire    ap_channel_done_opad_buffer_V_10;
wire    opad_buffer_V_10_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_10;
wire    ap_sync_channel_write_opad_buffer_V_10;
wire    ap_channel_done_opad_buffer_V_9;
wire    opad_buffer_V_9_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_9;
wire    ap_sync_channel_write_opad_buffer_V_9;
wire    ap_channel_done_opad_buffer_V_8;
wire    opad_buffer_V_8_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_8;
wire    ap_sync_channel_write_opad_buffer_V_8;
wire    ap_channel_done_opad_buffer_V_7;
wire    opad_buffer_V_7_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_7;
wire    ap_sync_channel_write_opad_buffer_V_7;
wire    ap_channel_done_opad_buffer_V_6;
wire    opad_buffer_V_6_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_6;
wire    ap_sync_channel_write_opad_buffer_V_6;
wire    ap_channel_done_opad_buffer_V_5;
wire    opad_buffer_V_5_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_5;
wire    ap_sync_channel_write_opad_buffer_V_5;
wire    ap_channel_done_opad_buffer_V_4;
wire    opad_buffer_V_4_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_4;
wire    ap_sync_channel_write_opad_buffer_V_4;
wire    ap_channel_done_opad_buffer_V_3;
wire    opad_buffer_V_3_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_3;
wire    ap_sync_channel_write_opad_buffer_V_3;
wire    ap_channel_done_opad_buffer_V_2;
wire    opad_buffer_V_2_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_2;
wire    ap_sync_channel_write_opad_buffer_V_2;
wire    ap_channel_done_opad_buffer_V_1;
wire    opad_buffer_V_1_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_1;
wire    ap_sync_channel_write_opad_buffer_V_1;
wire    ap_channel_done_opad_buffer_V_0;
wire    opad_buffer_V_0_full_n;
reg    ap_sync_reg_channel_write_opad_buffer_V_0;
wire    ap_sync_channel_write_opad_buffer_V_0;
wire   [383:0] HMAC_SHA384_2in1_120_U0_res_V_out;
wire    HMAC_SHA384_2in1_120_U0_ap_start;
wire    HMAC_SHA384_2in1_120_U0_res_V_out_ap_vld;
wire    HMAC_SHA384_2in1_120_U0_ap_done;
wire    HMAC_SHA384_2in1_120_U0_ap_ready;
wire    HMAC_SHA384_2in1_120_U0_ap_idle;
wire    HMAC_SHA384_2in1_120_U0_ap_continue;
wire    res_V_full_n;
wire    HMAC_SHA384_Block_entry817_proc_U0_ap_start;
wire    HMAC_SHA384_Block_entry817_proc_U0_ap_done;
wire    HMAC_SHA384_Block_entry817_proc_U0_ap_continue;
wire    HMAC_SHA384_Block_entry817_proc_U0_ap_idle;
wire    HMAC_SHA384_Block_entry817_proc_U0_ap_ready;
wire   [383:0] HMAC_SHA384_Block_entry817_proc_U0_ap_return;
wire    res_V_load_1_loc_channel_full_n;
wire    HMAC_SHA384_Block_entry818_proc_U0_ap_start;
wire    HMAC_SHA384_Block_entry818_proc_U0_ap_done;
wire    HMAC_SHA384_Block_entry818_proc_U0_ap_continue;
wire    HMAC_SHA384_Block_entry818_proc_U0_ap_idle;
wire    HMAC_SHA384_Block_entry818_proc_U0_ap_ready;
wire   [583:0] HMAC_SHA384_Block_entry818_proc_U0_output_r_TDATA;
wire    HMAC_SHA384_Block_entry818_proc_U0_output_r_TVALID;
wire    msg_key_strm_full_n;
wire   [511:0] msg_key_strm_dout;
wire   [5:0] msg_key_strm_num_data_valid;
wire   [5:0] msg_key_strm_fifo_cap;
wire    msg_key_strm_empty_n;
wire    len_strm_full_n;
wire   [39:0] len_strm_dout;
wire   [5:0] len_strm_num_data_valid;
wire   [5:0] len_strm_fifo_cap;
wire    len_strm_empty_n;
wire   [63:0] keep_V_dout;
wire   [3:0] keep_V_num_data_valid;
wire   [3:0] keep_V_fifo_cap;
wire    keep_V_empty_n;
wire   [5:0] id_V_dout;
wire   [3:0] id_V_num_data_valid;
wire   [3:0] id_V_fifo_cap;
wire    id_V_empty_n;
wire   [63:0] opad_buffer_V_0_dout;
wire   [1:0] opad_buffer_V_0_num_data_valid;
wire   [1:0] opad_buffer_V_0_fifo_cap;
wire    opad_buffer_V_0_empty_n;
wire   [63:0] opad_buffer_V_1_dout;
wire   [1:0] opad_buffer_V_1_num_data_valid;
wire   [1:0] opad_buffer_V_1_fifo_cap;
wire    opad_buffer_V_1_empty_n;
wire   [63:0] opad_buffer_V_2_dout;
wire   [1:0] opad_buffer_V_2_num_data_valid;
wire   [1:0] opad_buffer_V_2_fifo_cap;
wire    opad_buffer_V_2_empty_n;
wire   [63:0] opad_buffer_V_3_dout;
wire   [1:0] opad_buffer_V_3_num_data_valid;
wire   [1:0] opad_buffer_V_3_fifo_cap;
wire    opad_buffer_V_3_empty_n;
wire   [63:0] opad_buffer_V_4_dout;
wire   [1:0] opad_buffer_V_4_num_data_valid;
wire   [1:0] opad_buffer_V_4_fifo_cap;
wire    opad_buffer_V_4_empty_n;
wire   [63:0] opad_buffer_V_5_dout;
wire   [1:0] opad_buffer_V_5_num_data_valid;
wire   [1:0] opad_buffer_V_5_fifo_cap;
wire    opad_buffer_V_5_empty_n;
wire   [62:0] opad_buffer_V_6_dout;
wire   [1:0] opad_buffer_V_6_num_data_valid;
wire   [1:0] opad_buffer_V_6_fifo_cap;
wire    opad_buffer_V_6_empty_n;
wire   [62:0] opad_buffer_V_7_dout;
wire   [1:0] opad_buffer_V_7_num_data_valid;
wire   [1:0] opad_buffer_V_7_fifo_cap;
wire    opad_buffer_V_7_empty_n;
wire   [62:0] opad_buffer_V_8_dout;
wire   [1:0] opad_buffer_V_8_num_data_valid;
wire   [1:0] opad_buffer_V_8_fifo_cap;
wire    opad_buffer_V_8_empty_n;
wire   [62:0] opad_buffer_V_9_dout;
wire   [1:0] opad_buffer_V_9_num_data_valid;
wire   [1:0] opad_buffer_V_9_fifo_cap;
wire    opad_buffer_V_9_empty_n;
wire   [62:0] opad_buffer_V_10_dout;
wire   [1:0] opad_buffer_V_10_num_data_valid;
wire   [1:0] opad_buffer_V_10_fifo_cap;
wire    opad_buffer_V_10_empty_n;
wire   [62:0] opad_buffer_V_11_dout;
wire   [1:0] opad_buffer_V_11_num_data_valid;
wire   [1:0] opad_buffer_V_11_fifo_cap;
wire    opad_buffer_V_11_empty_n;
wire   [62:0] opad_buffer_V_12_dout;
wire   [1:0] opad_buffer_V_12_num_data_valid;
wire   [1:0] opad_buffer_V_12_fifo_cap;
wire    opad_buffer_V_12_empty_n;
wire   [62:0] opad_buffer_V_13_dout;
wire   [1:0] opad_buffer_V_13_num_data_valid;
wire   [1:0] opad_buffer_V_13_fifo_cap;
wire    opad_buffer_V_13_empty_n;
wire   [62:0] opad_buffer_V_14_dout;
wire   [1:0] opad_buffer_V_14_num_data_valid;
wire   [1:0] opad_buffer_V_14_fifo_cap;
wire    opad_buffer_V_14_empty_n;
wire   [62:0] opad_buffer_V_15_dout;
wire   [1:0] opad_buffer_V_15_num_data_valid;
wire   [1:0] opad_buffer_V_15_fifo_cap;
wire    opad_buffer_V_15_empty_n;
wire   [383:0] res_V_out_tmp_channel_dout;
wire   [1:0] res_V_out_tmp_channel_num_data_valid;
wire   [1:0] res_V_out_tmp_channel_fifo_cap;
wire    res_V_out_tmp_channel_empty_n;
wire   [383:0] res_V_dout;
wire   [1:0] res_V_num_data_valid;
wire   [1:0] res_V_fifo_cap;
wire    res_V_empty_n;
wire   [383:0] res_V_load_1_loc_channel_dout;
wire   [1:0] res_V_load_1_loc_channel_num_data_valid;
wire   [1:0] res_V_load_1_loc_channel_fifo_cap;
wire    res_V_load_1_loc_channel_empty_n;
wire   [0:0] start_for_HMAC_SHA384_2in119_U0_din;
wire    start_for_HMAC_SHA384_2in119_U0_full_n;
wire   [0:0] start_for_HMAC_SHA384_2in119_U0_dout;
wire    start_for_HMAC_SHA384_2in119_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_id_V = 1'b0;
#0 ap_sync_reg_channel_write_keep_V = 1'b0;
#0 ap_sync_reg_channel_write_res_V_out_tmp_channel = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_15 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_14 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_13 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_12 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_11 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_10 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_9 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_8 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_7 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_6 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_5 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_4 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_3 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_2 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_1 = 1'b0;
#0 ap_sync_reg_channel_write_opad_buffer_V_0 = 1'b0;
end

hmac_injectData18 injectData18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(injectData18_U0_ap_start),
    .start_full_n(start_for_HMAC_SHA384_2in119_U0_full_n),
    .ap_done(injectData18_U0_ap_done),
    .ap_continue(injectData18_U0_ap_continue),
    .ap_idle(injectData18_U0_ap_idle),
    .ap_ready(injectData18_U0_ap_ready),
    .start_out(injectData18_U0_start_out),
    .start_write(injectData18_U0_start_write),
    .input_r_TDATA(input_r_TDATA),
    .input_r_TVALID(input_r_TVALID),
    .input_r_TREADY(injectData18_U0_input_r_TREADY),
    .msg_key_strm167_din(injectData18_U0_msg_key_strm167_din),
    .msg_key_strm167_num_data_valid(msg_key_strm_num_data_valid),
    .msg_key_strm167_fifo_cap(msg_key_strm_fifo_cap),
    .msg_key_strm167_full_n(msg_key_strm_full_n),
    .msg_key_strm167_write(injectData18_U0_msg_key_strm167_write),
    .len_strm168_din(injectData18_U0_len_strm168_din),
    .len_strm168_num_data_valid(len_strm_num_data_valid),
    .len_strm168_fifo_cap(len_strm_fifo_cap),
    .len_strm168_full_n(len_strm_full_n),
    .len_strm168_write(injectData18_U0_len_strm168_write),
    .ap_return_0(injectData18_U0_ap_return_0),
    .ap_return_1(injectData18_U0_ap_return_1)
);

hmac_HMAC_SHA384_2in119 HMAC_SHA384_2in119_U0(
    .opad_buffer_0(HMAC_SHA384_2in119_U0_opad_buffer_0),
    .opad_buffer_1(HMAC_SHA384_2in119_U0_opad_buffer_1),
    .opad_buffer_2(HMAC_SHA384_2in119_U0_opad_buffer_2),
    .opad_buffer_3(HMAC_SHA384_2in119_U0_opad_buffer_3),
    .opad_buffer_4(HMAC_SHA384_2in119_U0_opad_buffer_4),
    .opad_buffer_5(HMAC_SHA384_2in119_U0_opad_buffer_5),
    .opad_buffer_6(HMAC_SHA384_2in119_U0_opad_buffer_6),
    .opad_buffer_7(HMAC_SHA384_2in119_U0_opad_buffer_7),
    .opad_buffer_8(HMAC_SHA384_2in119_U0_opad_buffer_8),
    .opad_buffer_9(HMAC_SHA384_2in119_U0_opad_buffer_9),
    .opad_buffer_10(HMAC_SHA384_2in119_U0_opad_buffer_10),
    .opad_buffer_11(HMAC_SHA384_2in119_U0_opad_buffer_11),
    .opad_buffer_12(HMAC_SHA384_2in119_U0_opad_buffer_12),
    .opad_buffer_13(HMAC_SHA384_2in119_U0_opad_buffer_13),
    .opad_buffer_14(HMAC_SHA384_2in119_U0_opad_buffer_14),
    .opad_buffer_15(HMAC_SHA384_2in119_U0_opad_buffer_15),
    .msg_key_strm167_dout(msg_key_strm_dout),
    .msg_key_strm167_empty_n(msg_key_strm_empty_n),
    .msg_key_strm167_read(HMAC_SHA384_2in119_U0_msg_key_strm167_read),
    .len_strm168_dout(len_strm_dout),
    .len_strm168_empty_n(len_strm_empty_n),
    .len_strm168_read(HMAC_SHA384_2in119_U0_len_strm168_read),
    .digest_output(HMAC_SHA384_2in119_U0_digest_output),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .opad_buffer_0_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_0_ap_vld),
    .opad_buffer_1_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_1_ap_vld),
    .opad_buffer_2_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_2_ap_vld),
    .opad_buffer_3_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_3_ap_vld),
    .opad_buffer_4_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_4_ap_vld),
    .opad_buffer_5_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_5_ap_vld),
    .opad_buffer_6_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_6_ap_vld),
    .opad_buffer_7_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_7_ap_vld),
    .opad_buffer_8_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_8_ap_vld),
    .opad_buffer_9_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_9_ap_vld),
    .opad_buffer_10_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_10_ap_vld),
    .opad_buffer_11_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_11_ap_vld),
    .opad_buffer_12_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_12_ap_vld),
    .opad_buffer_13_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_13_ap_vld),
    .opad_buffer_14_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_14_ap_vld),
    .opad_buffer_15_ap_vld(HMAC_SHA384_2in119_U0_opad_buffer_15_ap_vld),
    .ap_start(HMAC_SHA384_2in119_U0_ap_start),
    .ap_done(HMAC_SHA384_2in119_U0_ap_done),
    .digest_output_ap_vld(HMAC_SHA384_2in119_U0_digest_output_ap_vld),
    .ap_ready(HMAC_SHA384_2in119_U0_ap_ready),
    .ap_idle(HMAC_SHA384_2in119_U0_ap_idle),
    .ap_continue(HMAC_SHA384_2in119_U0_ap_continue)
);

hmac_HMAC_SHA384_2in1_120 HMAC_SHA384_2in1_120_U0(
    .opad_buffer_V_0(opad_buffer_V_0_dout),
    .opad_buffer_V_1(opad_buffer_V_1_dout),
    .opad_buffer_V_2(opad_buffer_V_2_dout),
    .opad_buffer_V_3(opad_buffer_V_3_dout),
    .opad_buffer_V_4(opad_buffer_V_4_dout),
    .opad_buffer_V_5(opad_buffer_V_5_dout),
    .opad_buffer_V_6(opad_buffer_V_6_dout),
    .opad_buffer_V_7(opad_buffer_V_7_dout),
    .opad_buffer_V_8(opad_buffer_V_8_dout),
    .opad_buffer_V_9(opad_buffer_V_9_dout),
    .opad_buffer_V_10(opad_buffer_V_10_dout),
    .opad_buffer_V_11(opad_buffer_V_11_dout),
    .opad_buffer_V_12(opad_buffer_V_12_dout),
    .opad_buffer_V_13(opad_buffer_V_13_dout),
    .opad_buffer_V_14(opad_buffer_V_14_dout),
    .opad_buffer_V_15(opad_buffer_V_15_dout),
    .res_V_in(res_V_out_tmp_channel_dout),
    .res_V_out(HMAC_SHA384_2in1_120_U0_res_V_out),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .opad_buffer_V_0_ap_vld(1'b0),
    .opad_buffer_V_1_ap_vld(1'b0),
    .opad_buffer_V_2_ap_vld(1'b0),
    .opad_buffer_V_3_ap_vld(1'b0),
    .opad_buffer_V_4_ap_vld(1'b0),
    .opad_buffer_V_5_ap_vld(1'b0),
    .opad_buffer_V_6_ap_vld(1'b0),
    .opad_buffer_V_7_ap_vld(1'b0),
    .opad_buffer_V_8_ap_vld(1'b0),
    .opad_buffer_V_9_ap_vld(1'b0),
    .opad_buffer_V_10_ap_vld(1'b0),
    .opad_buffer_V_11_ap_vld(1'b0),
    .opad_buffer_V_12_ap_vld(1'b0),
    .opad_buffer_V_13_ap_vld(1'b0),
    .opad_buffer_V_14_ap_vld(1'b0),
    .opad_buffer_V_15_ap_vld(1'b0),
    .res_V_in_ap_vld(1'b0),
    .ap_start(HMAC_SHA384_2in1_120_U0_ap_start),
    .res_V_out_ap_vld(HMAC_SHA384_2in1_120_U0_res_V_out_ap_vld),
    .ap_done(HMAC_SHA384_2in1_120_U0_ap_done),
    .ap_ready(HMAC_SHA384_2in1_120_U0_ap_ready),
    .ap_idle(HMAC_SHA384_2in1_120_U0_ap_idle),
    .ap_continue(HMAC_SHA384_2in1_120_U0_ap_continue)
);

hmac_HMAC_SHA384_Block_entry817_proc HMAC_SHA384_Block_entry817_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(HMAC_SHA384_Block_entry817_proc_U0_ap_start),
    .ap_done(HMAC_SHA384_Block_entry817_proc_U0_ap_done),
    .ap_continue(HMAC_SHA384_Block_entry817_proc_U0_ap_continue),
    .ap_idle(HMAC_SHA384_Block_entry817_proc_U0_ap_idle),
    .ap_ready(HMAC_SHA384_Block_entry817_proc_U0_ap_ready),
    .res_V(res_V_dout),
    .ap_return(HMAC_SHA384_Block_entry817_proc_U0_ap_return)
);

hmac_HMAC_SHA384_Block_entry818_proc HMAC_SHA384_Block_entry818_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(HMAC_SHA384_Block_entry818_proc_U0_ap_start),
    .ap_done(HMAC_SHA384_Block_entry818_proc_U0_ap_done),
    .ap_continue(HMAC_SHA384_Block_entry818_proc_U0_ap_continue),
    .ap_idle(HMAC_SHA384_Block_entry818_proc_U0_ap_idle),
    .ap_ready(HMAC_SHA384_Block_entry818_proc_U0_ap_ready),
    .p_read(keep_V_dout),
    .p_read1(id_V_dout),
    .p_read2(res_V_load_1_loc_channel_dout),
    .output_r_TDATA(HMAC_SHA384_Block_entry818_proc_U0_output_r_TDATA),
    .output_r_TVALID(HMAC_SHA384_Block_entry818_proc_U0_output_r_TVALID),
    .output_r_TREADY(output_r_TREADY)
);

hmac_fifo_w512_d32_D msg_key_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(injectData18_U0_msg_key_strm167_din),
    .if_full_n(msg_key_strm_full_n),
    .if_write(injectData18_U0_msg_key_strm167_write),
    .if_dout(msg_key_strm_dout),
    .if_num_data_valid(msg_key_strm_num_data_valid),
    .if_fifo_cap(msg_key_strm_fifo_cap),
    .if_empty_n(msg_key_strm_empty_n),
    .if_read(HMAC_SHA384_2in119_U0_msg_key_strm167_read)
);

hmac_fifo_w40_d32_D len_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(injectData18_U0_len_strm168_din),
    .if_full_n(len_strm_full_n),
    .if_write(injectData18_U0_len_strm168_write),
    .if_dout(len_strm_dout),
    .if_num_data_valid(len_strm_num_data_valid),
    .if_fifo_cap(len_strm_fifo_cap),
    .if_empty_n(len_strm_empty_n),
    .if_read(HMAC_SHA384_2in119_U0_len_strm168_read)
);

hmac_fifo_w64_d5_S keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(injectData18_U0_ap_return_0),
    .if_full_n(keep_V_full_n),
    .if_write(ap_channel_done_keep_V),
    .if_dout(keep_V_dout),
    .if_num_data_valid(keep_V_num_data_valid),
    .if_fifo_cap(keep_V_fifo_cap),
    .if_empty_n(keep_V_empty_n),
    .if_read(HMAC_SHA384_Block_entry818_proc_U0_ap_ready)
);

hmac_fifo_w6_d5_S id_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(injectData18_U0_ap_return_1),
    .if_full_n(id_V_full_n),
    .if_write(ap_channel_done_id_V),
    .if_dout(id_V_dout),
    .if_num_data_valid(id_V_num_data_valid),
    .if_fifo_cap(id_V_fifo_cap),
    .if_empty_n(id_V_empty_n),
    .if_read(HMAC_SHA384_Block_entry818_proc_U0_ap_ready)
);

hmac_fifo_w64_d2_S opad_buffer_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_0),
    .if_full_n(opad_buffer_V_0_full_n),
    .if_write(ap_channel_done_opad_buffer_V_0),
    .if_dout(opad_buffer_V_0_dout),
    .if_num_data_valid(opad_buffer_V_0_num_data_valid),
    .if_fifo_cap(opad_buffer_V_0_fifo_cap),
    .if_empty_n(opad_buffer_V_0_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w64_d2_S opad_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_1),
    .if_full_n(opad_buffer_V_1_full_n),
    .if_write(ap_channel_done_opad_buffer_V_1),
    .if_dout(opad_buffer_V_1_dout),
    .if_num_data_valid(opad_buffer_V_1_num_data_valid),
    .if_fifo_cap(opad_buffer_V_1_fifo_cap),
    .if_empty_n(opad_buffer_V_1_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w64_d2_S opad_buffer_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_2),
    .if_full_n(opad_buffer_V_2_full_n),
    .if_write(ap_channel_done_opad_buffer_V_2),
    .if_dout(opad_buffer_V_2_dout),
    .if_num_data_valid(opad_buffer_V_2_num_data_valid),
    .if_fifo_cap(opad_buffer_V_2_fifo_cap),
    .if_empty_n(opad_buffer_V_2_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w64_d2_S opad_buffer_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_3),
    .if_full_n(opad_buffer_V_3_full_n),
    .if_write(ap_channel_done_opad_buffer_V_3),
    .if_dout(opad_buffer_V_3_dout),
    .if_num_data_valid(opad_buffer_V_3_num_data_valid),
    .if_fifo_cap(opad_buffer_V_3_fifo_cap),
    .if_empty_n(opad_buffer_V_3_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w64_d2_S opad_buffer_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_4),
    .if_full_n(opad_buffer_V_4_full_n),
    .if_write(ap_channel_done_opad_buffer_V_4),
    .if_dout(opad_buffer_V_4_dout),
    .if_num_data_valid(opad_buffer_V_4_num_data_valid),
    .if_fifo_cap(opad_buffer_V_4_fifo_cap),
    .if_empty_n(opad_buffer_V_4_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w64_d2_S opad_buffer_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_5),
    .if_full_n(opad_buffer_V_5_full_n),
    .if_write(ap_channel_done_opad_buffer_V_5),
    .if_dout(opad_buffer_V_5_dout),
    .if_num_data_valid(opad_buffer_V_5_num_data_valid),
    .if_fifo_cap(opad_buffer_V_5_fifo_cap),
    .if_empty_n(opad_buffer_V_5_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_6),
    .if_full_n(opad_buffer_V_6_full_n),
    .if_write(ap_channel_done_opad_buffer_V_6),
    .if_dout(opad_buffer_V_6_dout),
    .if_num_data_valid(opad_buffer_V_6_num_data_valid),
    .if_fifo_cap(opad_buffer_V_6_fifo_cap),
    .if_empty_n(opad_buffer_V_6_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_7),
    .if_full_n(opad_buffer_V_7_full_n),
    .if_write(ap_channel_done_opad_buffer_V_7),
    .if_dout(opad_buffer_V_7_dout),
    .if_num_data_valid(opad_buffer_V_7_num_data_valid),
    .if_fifo_cap(opad_buffer_V_7_fifo_cap),
    .if_empty_n(opad_buffer_V_7_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_8),
    .if_full_n(opad_buffer_V_8_full_n),
    .if_write(ap_channel_done_opad_buffer_V_8),
    .if_dout(opad_buffer_V_8_dout),
    .if_num_data_valid(opad_buffer_V_8_num_data_valid),
    .if_fifo_cap(opad_buffer_V_8_fifo_cap),
    .if_empty_n(opad_buffer_V_8_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_9),
    .if_full_n(opad_buffer_V_9_full_n),
    .if_write(ap_channel_done_opad_buffer_V_9),
    .if_dout(opad_buffer_V_9_dout),
    .if_num_data_valid(opad_buffer_V_9_num_data_valid),
    .if_fifo_cap(opad_buffer_V_9_fifo_cap),
    .if_empty_n(opad_buffer_V_9_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_10),
    .if_full_n(opad_buffer_V_10_full_n),
    .if_write(ap_channel_done_opad_buffer_V_10),
    .if_dout(opad_buffer_V_10_dout),
    .if_num_data_valid(opad_buffer_V_10_num_data_valid),
    .if_fifo_cap(opad_buffer_V_10_fifo_cap),
    .if_empty_n(opad_buffer_V_10_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_11),
    .if_full_n(opad_buffer_V_11_full_n),
    .if_write(ap_channel_done_opad_buffer_V_11),
    .if_dout(opad_buffer_V_11_dout),
    .if_num_data_valid(opad_buffer_V_11_num_data_valid),
    .if_fifo_cap(opad_buffer_V_11_fifo_cap),
    .if_empty_n(opad_buffer_V_11_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_12),
    .if_full_n(opad_buffer_V_12_full_n),
    .if_write(ap_channel_done_opad_buffer_V_12),
    .if_dout(opad_buffer_V_12_dout),
    .if_num_data_valid(opad_buffer_V_12_num_data_valid),
    .if_fifo_cap(opad_buffer_V_12_fifo_cap),
    .if_empty_n(opad_buffer_V_12_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_13),
    .if_full_n(opad_buffer_V_13_full_n),
    .if_write(ap_channel_done_opad_buffer_V_13),
    .if_dout(opad_buffer_V_13_dout),
    .if_num_data_valid(opad_buffer_V_13_num_data_valid),
    .if_fifo_cap(opad_buffer_V_13_fifo_cap),
    .if_empty_n(opad_buffer_V_13_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_14),
    .if_full_n(opad_buffer_V_14_full_n),
    .if_write(ap_channel_done_opad_buffer_V_14),
    .if_dout(opad_buffer_V_14_dout),
    .if_num_data_valid(opad_buffer_V_14_num_data_valid),
    .if_fifo_cap(opad_buffer_V_14_fifo_cap),
    .if_empty_n(opad_buffer_V_14_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w63_d2_S opad_buffer_V_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_opad_buffer_15),
    .if_full_n(opad_buffer_V_15_full_n),
    .if_write(ap_channel_done_opad_buffer_V_15),
    .if_dout(opad_buffer_V_15_dout),
    .if_num_data_valid(opad_buffer_V_15_num_data_valid),
    .if_fifo_cap(opad_buffer_V_15_fifo_cap),
    .if_empty_n(opad_buffer_V_15_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w384_d2_S res_V_out_tmp_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in119_U0_digest_output),
    .if_full_n(res_V_out_tmp_channel_full_n),
    .if_write(ap_channel_done_res_V_out_tmp_channel),
    .if_dout(res_V_out_tmp_channel_dout),
    .if_num_data_valid(res_V_out_tmp_channel_num_data_valid),
    .if_fifo_cap(res_V_out_tmp_channel_fifo_cap),
    .if_empty_n(res_V_out_tmp_channel_empty_n),
    .if_read(HMAC_SHA384_2in1_120_U0_ap_ready)
);

hmac_fifo_w384_d2_S res_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_2in1_120_U0_res_V_out),
    .if_full_n(res_V_full_n),
    .if_write(HMAC_SHA384_2in1_120_U0_ap_done),
    .if_dout(res_V_dout),
    .if_num_data_valid(res_V_num_data_valid),
    .if_fifo_cap(res_V_fifo_cap),
    .if_empty_n(res_V_empty_n),
    .if_read(HMAC_SHA384_Block_entry817_proc_U0_ap_ready)
);

hmac_fifo_w384_d2_S res_V_load_1_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HMAC_SHA384_Block_entry817_proc_U0_ap_return),
    .if_full_n(res_V_load_1_loc_channel_full_n),
    .if_write(HMAC_SHA384_Block_entry817_proc_U0_ap_done),
    .if_dout(res_V_load_1_loc_channel_dout),
    .if_num_data_valid(res_V_load_1_loc_channel_num_data_valid),
    .if_fifo_cap(res_V_load_1_loc_channel_fifo_cap),
    .if_empty_n(res_V_load_1_loc_channel_empty_n),
    .if_read(HMAC_SHA384_Block_entry818_proc_U0_ap_ready)
);

hmac_start_for_HMAC_SHA384_2in119_U0 start_for_HMAC_SHA384_2in119_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_HMAC_SHA384_2in119_U0_din),
    .if_full_n(start_for_HMAC_SHA384_2in119_U0_full_n),
    .if_write(injectData18_U0_start_write),
    .if_dout(start_for_HMAC_SHA384_2in119_U0_dout),
    .if_empty_n(start_for_HMAC_SHA384_2in119_U0_empty_n),
    .if_read(HMAC_SHA384_2in119_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_id_V <= 1'b0;
    end else begin
        if (((injectData18_U0_ap_done & injectData18_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_id_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_id_V <= ap_sync_channel_write_id_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_keep_V <= 1'b0;
    end else begin
        if (((injectData18_U0_ap_done & injectData18_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_keep_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_keep_V <= ap_sync_channel_write_keep_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_0 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_0 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_0 <= ap_sync_channel_write_opad_buffer_V_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_1 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_1 <= ap_sync_channel_write_opad_buffer_V_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_10 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_10 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_10 <= ap_sync_channel_write_opad_buffer_V_10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_11 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_11 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_11 <= ap_sync_channel_write_opad_buffer_V_11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_12 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_12 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_12 <= ap_sync_channel_write_opad_buffer_V_12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_13 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_13 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_13 <= ap_sync_channel_write_opad_buffer_V_13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_14 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_14 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_14 <= ap_sync_channel_write_opad_buffer_V_14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_15 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_15 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_15 <= ap_sync_channel_write_opad_buffer_V_15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_2 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_2 <= ap_sync_channel_write_opad_buffer_V_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_3 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_3 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_3 <= ap_sync_channel_write_opad_buffer_V_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_4 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_4 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_4 <= ap_sync_channel_write_opad_buffer_V_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_5 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_5 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_5 <= ap_sync_channel_write_opad_buffer_V_5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_6 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_6 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_6 <= ap_sync_channel_write_opad_buffer_V_6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_7 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_7 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_7 <= ap_sync_channel_write_opad_buffer_V_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_8 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_8 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_8 <= ap_sync_channel_write_opad_buffer_V_8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_opad_buffer_V_9 <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_opad_buffer_V_9 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_opad_buffer_V_9 <= ap_sync_channel_write_opad_buffer_V_9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_res_V_out_tmp_channel <= 1'b0;
    end else begin
        if (((HMAC_SHA384_2in119_U0_ap_done & HMAC_SHA384_2in119_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_V_out_tmp_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_V_out_tmp_channel <= ap_sync_channel_write_res_V_out_tmp_channel;
        end
    end
end

assign HMAC_SHA384_2in119_U0_ap_continue = (ap_sync_channel_write_res_V_out_tmp_channel & ap_sync_channel_write_opad_buffer_V_9 & ap_sync_channel_write_opad_buffer_V_8 & ap_sync_channel_write_opad_buffer_V_7 & ap_sync_channel_write_opad_buffer_V_6 & ap_sync_channel_write_opad_buffer_V_5 & ap_sync_channel_write_opad_buffer_V_4 & ap_sync_channel_write_opad_buffer_V_3 & ap_sync_channel_write_opad_buffer_V_2 & ap_sync_channel_write_opad_buffer_V_15 & ap_sync_channel_write_opad_buffer_V_14 & ap_sync_channel_write_opad_buffer_V_13 & ap_sync_channel_write_opad_buffer_V_12 & ap_sync_channel_write_opad_buffer_V_11 & ap_sync_channel_write_opad_buffer_V_10 & ap_sync_channel_write_opad_buffer_V_1 & ap_sync_channel_write_opad_buffer_V_0);

assign HMAC_SHA384_2in119_U0_ap_start = start_for_HMAC_SHA384_2in119_U0_empty_n;

assign HMAC_SHA384_2in1_120_U0_ap_continue = res_V_full_n;

assign HMAC_SHA384_2in1_120_U0_ap_start = (res_V_out_tmp_channel_empty_n & opad_buffer_V_9_empty_n & opad_buffer_V_8_empty_n & opad_buffer_V_7_empty_n & opad_buffer_V_6_empty_n & opad_buffer_V_5_empty_n & opad_buffer_V_4_empty_n & opad_buffer_V_3_empty_n & opad_buffer_V_2_empty_n & opad_buffer_V_1_empty_n & opad_buffer_V_15_empty_n & opad_buffer_V_14_empty_n & opad_buffer_V_13_empty_n & opad_buffer_V_12_empty_n & opad_buffer_V_11_empty_n & opad_buffer_V_10_empty_n & opad_buffer_V_0_empty_n);

assign HMAC_SHA384_Block_entry817_proc_U0_ap_continue = res_V_load_1_loc_channel_full_n;

assign HMAC_SHA384_Block_entry817_proc_U0_ap_start = res_V_empty_n;

assign HMAC_SHA384_Block_entry818_proc_U0_ap_continue = ap_continue;

assign HMAC_SHA384_Block_entry818_proc_U0_ap_start = (res_V_load_1_loc_channel_empty_n & keep_V_empty_n & id_V_empty_n);

assign ap_channel_done_id_V = (injectData18_U0_ap_done & (ap_sync_reg_channel_write_id_V ^ 1'b1));

assign ap_channel_done_keep_V = (injectData18_U0_ap_done & (ap_sync_reg_channel_write_keep_V ^ 1'b1));

assign ap_channel_done_opad_buffer_V_0 = ((ap_sync_reg_channel_write_opad_buffer_V_0 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_1 = ((ap_sync_reg_channel_write_opad_buffer_V_1 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_10 = ((ap_sync_reg_channel_write_opad_buffer_V_10 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_11 = ((ap_sync_reg_channel_write_opad_buffer_V_11 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_12 = ((ap_sync_reg_channel_write_opad_buffer_V_12 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_13 = ((ap_sync_reg_channel_write_opad_buffer_V_13 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_14 = ((ap_sync_reg_channel_write_opad_buffer_V_14 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_15 = ((ap_sync_reg_channel_write_opad_buffer_V_15 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_2 = ((ap_sync_reg_channel_write_opad_buffer_V_2 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_3 = ((ap_sync_reg_channel_write_opad_buffer_V_3 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_4 = ((ap_sync_reg_channel_write_opad_buffer_V_4 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_5 = ((ap_sync_reg_channel_write_opad_buffer_V_5 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_6 = ((ap_sync_reg_channel_write_opad_buffer_V_6 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_7 = ((ap_sync_reg_channel_write_opad_buffer_V_7 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_8 = ((ap_sync_reg_channel_write_opad_buffer_V_8 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_opad_buffer_V_9 = ((ap_sync_reg_channel_write_opad_buffer_V_9 ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_channel_done_res_V_out_tmp_channel = ((ap_sync_reg_channel_write_res_V_out_tmp_channel ^ 1'b1) & HMAC_SHA384_2in119_U0_ap_done);

assign ap_done = HMAC_SHA384_Block_entry818_proc_U0_ap_done;

assign ap_idle = (injectData18_U0_ap_idle & (res_V_load_1_loc_channel_empty_n ^ 1'b1) & (res_V_empty_n ^ 1'b1) & (res_V_out_tmp_channel_empty_n ^ 1'b1) & (opad_buffer_V_15_empty_n ^ 1'b1) & (opad_buffer_V_14_empty_n ^ 1'b1) & (opad_buffer_V_13_empty_n ^ 1'b1) & (opad_buffer_V_12_empty_n ^ 1'b1) & (opad_buffer_V_11_empty_n ^ 1'b1) & (opad_buffer_V_10_empty_n ^ 1'b1) & (opad_buffer_V_9_empty_n ^ 1'b1) & (opad_buffer_V_8_empty_n ^ 1'b1) & (opad_buffer_V_7_empty_n ^ 1'b1) & (opad_buffer_V_6_empty_n ^ 1'b1) & (opad_buffer_V_5_empty_n ^ 1'b1) & (opad_buffer_V_4_empty_n ^ 1'b1) & (opad_buffer_V_3_empty_n ^ 1'b1) & (opad_buffer_V_2_empty_n ^ 1'b1) & (opad_buffer_V_1_empty_n ^ 1'b1) & (opad_buffer_V_0_empty_n ^ 1'b1) & (id_V_empty_n ^ 1'b1) & (keep_V_empty_n ^ 1'b1) & HMAC_SHA384_Block_entry818_proc_U0_ap_idle & HMAC_SHA384_Block_entry817_proc_U0_ap_idle & HMAC_SHA384_2in1_120_U0_ap_idle & HMAC_SHA384_2in119_U0_ap_idle);

assign ap_ready = injectData18_U0_ap_ready;

assign ap_sync_channel_write_id_V = ((id_V_full_n & ap_channel_done_id_V) | ap_sync_reg_channel_write_id_V);

assign ap_sync_channel_write_keep_V = ((keep_V_full_n & ap_channel_done_keep_V) | ap_sync_reg_channel_write_keep_V);

assign ap_sync_channel_write_opad_buffer_V_0 = ((opad_buffer_V_0_full_n & ap_channel_done_opad_buffer_V_0) | ap_sync_reg_channel_write_opad_buffer_V_0);

assign ap_sync_channel_write_opad_buffer_V_1 = ((opad_buffer_V_1_full_n & ap_channel_done_opad_buffer_V_1) | ap_sync_reg_channel_write_opad_buffer_V_1);

assign ap_sync_channel_write_opad_buffer_V_10 = ((opad_buffer_V_10_full_n & ap_channel_done_opad_buffer_V_10) | ap_sync_reg_channel_write_opad_buffer_V_10);

assign ap_sync_channel_write_opad_buffer_V_11 = ((opad_buffer_V_11_full_n & ap_channel_done_opad_buffer_V_11) | ap_sync_reg_channel_write_opad_buffer_V_11);

assign ap_sync_channel_write_opad_buffer_V_12 = ((opad_buffer_V_12_full_n & ap_channel_done_opad_buffer_V_12) | ap_sync_reg_channel_write_opad_buffer_V_12);

assign ap_sync_channel_write_opad_buffer_V_13 = ((opad_buffer_V_13_full_n & ap_channel_done_opad_buffer_V_13) | ap_sync_reg_channel_write_opad_buffer_V_13);

assign ap_sync_channel_write_opad_buffer_V_14 = ((opad_buffer_V_14_full_n & ap_channel_done_opad_buffer_V_14) | ap_sync_reg_channel_write_opad_buffer_V_14);

assign ap_sync_channel_write_opad_buffer_V_15 = ((opad_buffer_V_15_full_n & ap_channel_done_opad_buffer_V_15) | ap_sync_reg_channel_write_opad_buffer_V_15);

assign ap_sync_channel_write_opad_buffer_V_2 = ((opad_buffer_V_2_full_n & ap_channel_done_opad_buffer_V_2) | ap_sync_reg_channel_write_opad_buffer_V_2);

assign ap_sync_channel_write_opad_buffer_V_3 = ((opad_buffer_V_3_full_n & ap_channel_done_opad_buffer_V_3) | ap_sync_reg_channel_write_opad_buffer_V_3);

assign ap_sync_channel_write_opad_buffer_V_4 = ((opad_buffer_V_4_full_n & ap_channel_done_opad_buffer_V_4) | ap_sync_reg_channel_write_opad_buffer_V_4);

assign ap_sync_channel_write_opad_buffer_V_5 = ((opad_buffer_V_5_full_n & ap_channel_done_opad_buffer_V_5) | ap_sync_reg_channel_write_opad_buffer_V_5);

assign ap_sync_channel_write_opad_buffer_V_6 = ((opad_buffer_V_6_full_n & ap_channel_done_opad_buffer_V_6) | ap_sync_reg_channel_write_opad_buffer_V_6);

assign ap_sync_channel_write_opad_buffer_V_7 = ((opad_buffer_V_7_full_n & ap_channel_done_opad_buffer_V_7) | ap_sync_reg_channel_write_opad_buffer_V_7);

assign ap_sync_channel_write_opad_buffer_V_8 = ((opad_buffer_V_8_full_n & ap_channel_done_opad_buffer_V_8) | ap_sync_reg_channel_write_opad_buffer_V_8);

assign ap_sync_channel_write_opad_buffer_V_9 = ((opad_buffer_V_9_full_n & ap_channel_done_opad_buffer_V_9) | ap_sync_reg_channel_write_opad_buffer_V_9);

assign ap_sync_channel_write_res_V_out_tmp_channel = ((res_V_out_tmp_channel_full_n & ap_channel_done_res_V_out_tmp_channel) | ap_sync_reg_channel_write_res_V_out_tmp_channel);

assign injectData18_U0_ap_continue = (ap_sync_channel_write_keep_V & ap_sync_channel_write_id_V);

assign injectData18_U0_ap_start = ap_start;

assign input_r_TREADY = injectData18_U0_input_r_TREADY;

assign output_r_TDATA = HMAC_SHA384_Block_entry818_proc_U0_output_r_TDATA;

assign output_r_TVALID = HMAC_SHA384_Block_entry818_proc_U0_output_r_TVALID;

assign start_for_HMAC_SHA384_2in119_U0_din = 1'b1;

endmodule //hmac_HMAC_SHA384
